import 'package:food_app/constants.dart';
import 'package:food_app/models/FoodData.dart';
import 'package:food_app/models/description.dart';
import 'package:food_app/models/images_source.dart';

final List<FoodData> immunityFoodList = [
  FoodData(
      id: 1,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 2,
      title: "ليمون",
      description: lemon_des,
      amountScale: mediumAmount,
      image: lemon_image,
      calories: 17,
      protein: 0.6,
      fat: 0.2,
      carb: 5),
  FoodData(
      id: 3,
      title: "جريب فروت",
      description: grapefruit_des,
      amountScale: mediumAmount,
      image: grapefruit_image,
      calories: 82,
      protein: 1.6,
      fat: 0.3,
      carb: 20.7),
  FoodData(
      id: 4,
      title: "يوسفي",
      description: mandarin_des,
      amountScale: mediumAmount,
      image: mandarin_image,
      calories: 47,
      protein: 0.7,
      fat: 0.3,
      carb: 11.7),
  FoodData(
      id: 5,
      title: "توت الأزرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 6,
      title: "توت العليق",
      description: raspberry_des,
      amountScale: gramAmount,
      image: raspberry_image,
      calories: 53,
      protein: 1.2,
      fat: 0.7,
      carb: 12),
  FoodData(
      id: 7,
      title: "بطيخ",
      description: watermelon_des,
      amountScale: gramAmount,
      image: watermelon_image,
      calories: 30,
      protein: 0.6,
      fat: 0.2,
      carb: 8),
  FoodData(
      id: 8,
      title: "رمان",
      description: pomegranate_des,
      amountScale: gramAmount,
      image: pomegranate_image,
      calories: 83,
      protein: 1.7,
      fat: 1.1,
      carb: 18.7),
  FoodData(
      id: 9,
      title: "مشروم",
      description: mashroom_des,
      amountScale: gramAmount,
      image: mashroom_image,
      calories: 22,
      protein: 3.1,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 10,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 11,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 12,
      title: "فلفل حلو",
      description: pepper_des,
      amountScale: gramAmount,
      image: pepper_image,
      calories: 40,
      protein: 2,
      fat: 0.2,
      carb: 9),
  FoodData(
      id: 13,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 14,
      title: "لب سوري",
      description: sunflowerPulp_des,
      amountScale: gramAmount,
      image: sunflowerPulp_image,
      calories: 619,
      protein: 17.2,
      fat: 56.8,
      carb: 20.6),
  FoodData(
      id: 15,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 16,
      title: "ثوم",
      description: garlic_des,
      amountScale: gramAmount,
      image: garlic_image,
      calories: 149,
      protein: 6.4,
      fat: 0.5,
      carb: 33),
  FoodData(
      id: 17,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 18,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 19,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 20,
      title: "افخاد الدجاج",
      description: chickenLegs_des,
      amountScale: gramAmount,
      image: chickenLegs_image,
      calories: 209,
      protein: 26,
      fat: 10.9,
      carb: 0),
];
final List<FoodData> anemiaFoodList = [
  FoodData(
      id: 1,
      title: "لحم بقري",
      description: beef_des,
      amountScale: gramAmount,
      image: beef_image,
      calories: 217,
      protein: 26.1,
      fat: 11.8,
      carb: 0),
  FoodData(
      id: 2,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 3,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 4,
      title: "افخاد الدجاج",
      description: chickenLegs_des,
      amountScale: gramAmount,
      image: chickenLegs_image,
      calories: 209,
      protein: 26,
      fat: 10.9,
      carb: 0),
  FoodData(
      id: 5,
      title: "لحم الديك الرومي",
      description: turkey_des,
      amountScale: gramAmount,
      image: turkey_image,
      calories: 147,
      protein: 30,
      fat: 2.2,
      carb: 0),
  FoodData(
      id: 6,
      title: "لحم البط",
      description: duck_des,
      amountScale: gramAmount,
      image: duck_image,
      calories: 337,
      protein: 19,
      fat: 28,
      carb: 0),
  FoodData(
      id: 7,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 8,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 9,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 10,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 11,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 12,
      title: "بازلاء",
      description: chickpea_des,
      amountScale: gramAmount,
      image: chickpea_image,
      calories: 81,
      protein: 5,
      fat: 0.4,
      carb: 14),
  FoodData(
      id: 13,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 14,
      title: "سلق",
      description: salq_des,
      amountScale: gramAmount,
      image: salq_image,
      calories: 19,
      protein: 1.8,
      fat: 3.7,
      carb: 0.2),
  FoodData(
      id: 15,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 16,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 17,
      title: "ليمون",
      description: lemon_des,
      amountScale: mediumAmount,
      image: lemon_image,
      calories: 17,
      protein: 0.6,
      fat: 0.2,
      carb: 5),
  FoodData(
      id: 18,
      title: "جريب فروت",
      description: grapefruit_des,
      amountScale: mediumAmount,
      image: grapefruit_image,
      calories: 82,
      protein: 1.6,
      fat: 0.3,
      carb: 20.7),
  FoodData(
      id: 19,
      title: "فراولة",
      description: strawberry_des,
      amountScale: gramAmount,
      image: strawberry_image,
      calories: 33,
      protein: 0.7,
      fat: 0.3,
      carb: 8),
  FoodData(
      id: 20,
      title: "كيوي",
      description: kiwi_des,
      amountScale: mediumAmount,
      image: kiwi_image,
      calories: 42,
      protein: 0.8,
      fat: 0.4,
      carb: 10),
  FoodData(
      id: 21,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 22,
      title: "فلفل حلو",
      description: pepper_des,
      amountScale: gramAmount,
      image: pepper_image,
      calories: 40,
      protein: 2,
      fat: 0.2,
      carb: 9),
  FoodData(
      id: 23,
      title: "طماطم",
      description: tomato_des,
      amountScale: gramAmount,
      image: tomato_image,
      calories: 18,
      protein: 0.9,
      fat: 0.2,
      carb: 3.9),
  FoodData(
      id: 24,
      title: "جمبري",
      description: shrimp_des,
      amountScale: gramAmount,
      image: shrimp_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 25,
      title: "محار البحر",
      description: mahar_des,
      amountScale: gramAmount,
      image: mahar_image,
      calories: 86,
      protein: 12,
      fat: 2.5,
      carb: 4),
];
final List<FoodData> colonFoodList = [
  FoodData(
      id: 1,
      title: "تفاح",
      description: apple_des,
      amountScale: mediumAmount,
      image: apple_image,
      calories: 95,
      protein: 0.5,
      fat: 0.3,
      carb: 25),
  FoodData(
      id: 2,
      title: "توت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 3,
      title: "توت العليق",
      description: raspberry_des,
      amountScale: gramAmount,
      image: raspberry_image,
      calories: 53,
      protein: 1.2,
      fat: 0.7,
      carb: 12),
  FoodData(
      id: 4,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 5,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 6,
      title: "كمثرى",
      description: peer_des,
      amountScale: mediumAmount,
      image: peer_image,
      calories: 103,
      protein: 0.7,
      fat: 0.2,
      carb: 27.5),
  FoodData(
      id: 7,
      title: "خس",
      description: lettuce_des,
      amountScale: gramAmount,
      image: lettuce_image,
      calories: 17,
      protein: 1.2,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 8,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 9,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
  FoodData(
      id: 10,
      title: "جزر",
      description: carrot_des,
      amountScale: gramAmount,
      image: carrot_image,
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carb: 10),
  FoodData(
      id: 11,
      title: "باميا",
      description: okra_des,
      amountScale: gramAmount,
      image: okra_image,
      calories: 33,
      protein: 1.9,
      fat: 0.2,
      carb: 7),
  FoodData(
      id: 12,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 13,
      title: "شوفان",
      description: oats_des,
      amountScale: gramAmount,
      image: oats_image,
      calories: 389,
      protein: 17,
      fat: 7,
      carb: 66.3),
  FoodData(
      id: 14,
      title: "أرز بني",
      description: brownRice_des,
      amountScale: gramAmount,
      image: brownRice_image,
      calories: 370,
      protein: 8,
      fat: 2.9,
      carb: 77),
  FoodData(
      id: 15,
      title: "خبز بلدي مصري",
      description: egyptionBread_des,
      amountScale: mediumAmount,
      image: egyptionBread_image,
      calories: 300,
      protein: 9.5,
      fat: 4.3,
      carb: 56),
  FoodData(
      id: 16,
      title: "خبز نخالة",
      description: nokhalaBread_des,
      amountScale: mediumAmount,
      image: nokhalaBread_image,
      calories: 313,
      protein: 13,
      fat: 4.3,
      carb: 56),
  FoodData(
      id: 17,
      title: "شعير",
      description: barley_des,
      amountScale: gramAmount,
      image: barley_image,
      calories: 354,
      protein: 12,
      fat: 2.3,
      carb: 73),
  FoodData(
      id: 18,
      title: "زيت الزيتون",
      description: oliveOil_des,
      amountScale: sponAmount,
      image: oliveOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 19,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 20,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 21,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
];
final List<FoodData> cancerFoodList = [
  FoodData(
      id: 1,
      title: "ثوم",
      description: garlic_des,
      amountScale: gramAmount,
      image: garlic_image,
      calories: 149,
      protein: 6.4,
      fat: 0.5,
      carb: 33),
  FoodData(
      id: 2,
      title: "طماطم",
      description: tomato_des,
      amountScale: gramAmount,
      image: tomato_image,
      calories: 18,
      protein: 0.9,
      fat: 0.2,
      carb: 3.9),
  FoodData(
      id: 3,
      title: "جزر",
      description: carrot_des,
      amountScale: gramAmount,
      image: carrot_image,
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carb: 10),
  FoodData(
      id: 4,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 5,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
  FoodData(
      id: 6,
      title: "قرنبيط",
      description: qarnabeet_des,
      amountScale: gramAmount,
      image: qarnabeet_image,
      calories: 25,
      protein: 1.9,
      fat: 0.3,
      carb: 5),
  FoodData(
      id: 7,
      title: "فراولة",
      description: strawberry_des,
      amountScale: gramAmount,
      image: strawberry_image,
      calories: 33,
      protein: 0.7,
      fat: 0.3,
      carb: 8),
  FoodData(
      id: 8,
      title: "توت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 9,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 10,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 11,
      title: "فلفل حلو",
      description: pepper_des,
      amountScale: gramAmount,
      image: pepper_image,
      calories: 40,
      protein: 2,
      fat: 0.2,
      carb: 9),
  FoodData(
      id: 12,
      title: "بنجر",
      description: beetroot_des,
      amountScale: gramAmount,
      image: beetroot_image,
      calories: 43,
      protein: 1.6,
      fat: 0.2,
      carb: 9.5),
  FoodData(
      id: 13,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
];
final List<FoodData> constipationFoodList = [
  FoodData(
      id: 1,
      title: "بذور الكتان",
      description: kettan_des,
      amountScale: gramAmount,
      image: kettan_image,
      calories: 534,
      protein: 18,
      fat: 42,
      carb: 29),
  FoodData(
      id: 2,
      title: "بذور الشيا",
      description: chia_des,
      amountScale: gramAmount,
      image: chia_image,
      calories: 486,
      protein: 17,
      fat: 31,
      carb: 42),
  FoodData(
      id: 3,
      title: "فشار",
      description: popcorn_des,
      amountScale: gramAmount,
      image: popcorn_image,
      calories: 375,
      protein: 11,
      fat: 4.3,
      carb: 74),
  FoodData(
      id: 4,
      title: "تفاح",
      description: apple_des,
      amountScale: mediumAmount,
      image: apple_image,
      calories: 95,
      protein: 0.5,
      fat: 0.3,
      carb: 25),
  FoodData(
      id: 5,
      title: "كيوي",
      description: kiwi_des,
      amountScale: mediumAmount,
      image: kiwi_image,
      calories: 42,
      protein: 0.8,
      fat: 0.4,
      carb: 10),
  FoodData(
      id: 6,
      title: "خوخ",
      description: peach_des,
      amountScale: mediumAmount,
      image: peach_image,
      calories: 50,
      protein: 1,
      fat: 0.5,
      carb: 15),
  FoodData(
      id: 7,
      title: "تين",
      description: fig_des,
      amountScale: mediumAmount,
      image: fig_image,
      calories: 37,
      protein: 0.38,
      fat: 0.15,
      carb: 9.6),
  FoodData(
      id: 8,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 9,
      title: "جريب فروت",
      description: grapefruit_des,
      amountScale: mediumAmount,
      image: grapefruit_image,
      calories: 82,
      protein: 1.6,
      fat: 0.3,
      carb: 20.7),
  FoodData(
      id: 10,
      title: "يوسفي",
      description: mandarin_des,
      amountScale: mediumAmount,
      image: mandarin_image,
      calories: 47,
      protein: 0.7,
      fat: 0.3,
      carb: 11.7),
]; //الامساك
final List<FoodData> diarrheaFoodList = [
  FoodData(
      id: 1,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 2,
      title: "خبز أبيض",
      description: whiteBread_des,
      amountScale: mediumAmount,
      image: whiteBread_image,
      calories: 266,
      protein: 9.8,
      fat: 2.6,
      carb: 55),
  FoodData(
      id: 3,
      title: "أرز أبيض",
      description: whiteRice_des,
      amountScale: gramAmount,
      image: whiteRice_image,
      calories: 360,
      protein: 7,
      fat: 0.6,
      carb: 79),
  FoodData(
      id: 4,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
  FoodData(
      id: 5,
      title: "بطاطس",
      description: potato_des,
      amountScale: gramAmount,
      image: potato_image,
      calories: 77,
      protein: 2,
      fat: 0.1,
      carb: 17),
  FoodData(
      id: 6,
      title: "تفاح",
      description: apple_des,
      amountScale: mediumAmount,
      image: apple_image,
      calories: 95,
      protein: 0.5,
      fat: 0.3,
      carb: 25),
  FoodData(
      id: 7,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 8,
      title: "افخاد الدجاج",
      description: chickenLegs_des,
      amountScale: gramAmount,
      image: chickenLegs_image,
      calories: 209,
      protein: 26,
      fat: 10.9,
      carb: 0),
  FoodData(
      id: 9,
      title: "لحم الديك الرومي",
      description: turkey_des,
      amountScale: gramAmount,
      image: turkey_image,
      calories: 147,
      protein: 30,
      fat: 2.2,
      carb: 0),
  FoodData(
      id: 10,
      title: "توت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 11,
      title: "عنب",
      description: grabe_des,
      amountScale: gramAmount,
      image: grabe_image,
      calories: 67,
      protein: 0.6,
      fat: 0.4,
      carb: 17),
]; // الاسهال
final List<FoodData> moodFoodList = [
  FoodData(
      id: 1,
      title: "شوكولاتة",
      description: chocolate_des,
      amountScale: gramAmount,
      image: chocolate_image,
      calories: 546,
      protein: 4.9,
      fat: 31,
      carb: 61),
  FoodData(
      id: 2,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 3,
      title: "توت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 4,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 5,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 6,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 7,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 8,
      title: "جمبري",
      description: shrimp_des,
      amountScale: gramAmount,
      image: shrimp_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 9,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 10,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 11,
      title: "سمك ماكريل",
      description: makarelFish_des,
      amountScale: gramAmount,
      image: makarelFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 12,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 13,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
  FoodData(
      id: 14,
      title: "سلق",
      description: salq_des,
      amountScale: gramAmount,
      image: salq_image,
      calories: 19,
      protein: 1.8,
      fat: 3.7,
      carb: 0.2),
  FoodData(
      id: 15,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 16,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
];
final List<FoodData> jointPainFoodList = [
  FoodData(
      id: 1,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 2,
      title: "سمك ماكريل",
      description: makarelFish_des,
      amountScale: gramAmount,
      image: makarelFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 3,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 4,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 5,
      title: "ثوم",
      description: garlic_des,
      amountScale: gramAmount,
      image: garlic_image,
      calories: 149,
      protein: 6.4,
      fat: 0.5,
      carb: 33),
  FoodData(
      id: 6,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 7,
      title: "استاكوزا",
      description: estakoza_des,
      amountScale: gramAmount,
      image: estakoza_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 8,
      title: "فول سوداني",
      description: peanut_des,
      amountScale: gramAmount,
      image: peanut_image,
      calories: 567,
      protein: 25.8,
      fat: 49.2,
      carb: 16.1),
  FoodData(
      id: 9,
      title: "فلفل حار",
      description: chilli_des,
      amountScale: gramAmount,
      image: chilli_image,
      calories: 40,
      protein: 1.9,
      fat: 0.4,
      carb: 9),
  FoodData(
      id: 10,
      title: "زنجبيل",
      description: ginger_des,
      amountScale: gramAmount,
      image: ginger_image,
      calories: 80,
      protein: 1.8,
      fat: 0.8,
      carb: 18),
  FoodData(
      id: 11,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 12,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 13,
      title: "توت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 14,
      title: "عنب",
      description: grabe_des,
      amountScale: gramAmount,
      image: grabe_image,
      calories: 67,
      protein: 0.6,
      fat: 0.4,
      carb: 17),
  FoodData(
      id: 15,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 16,
      title: "زيت الزيتون",
      description: oliveOil_des,
      amountScale: sponAmount,
      image: oliveOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
];
final List<FoodData> highPressureFoodList = [
  FoodData(
      id: 1,
      title: "تفاح",
      description: apple_des,
      amountScale: mediumAmount,
      image: apple_image,
      calories: 95,
      protein: 0.5,
      fat: 0.3,
      carb: 25),
  FoodData(
      id: 2,
      title: "مشمش",
      description: apricot_des,
      amountScale: mediumAmount,
      image: apricot_image,
      calories: 17,
      protein: 0.5,
      fat: 0.1,
      carb: 3.9),
  FoodData(
      id: 3,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 4,
      title: "عنب",
      description: grabe_des,
      amountScale: gramAmount,
      image: grabe_image,
      calories: 67,
      protein: 0.6,
      fat: 0.4,
      carb: 17),
  FoodData(
      id: 5,
      title: "مانجا",
      description: mango_des,
      amountScale: mediumAmount,
      image: mango_image,
      calories: 201,
      protein: 2.8,
      fat: 1.3,
      carb: 50),
  FoodData(
      id: 6,
      title: "بطيخ",
      description: watermelon_des,
      amountScale: gramAmount,
      image: watermelon_image,
      calories: 30,
      protein: 0.6,
      fat: 0.2,
      carb: 8),
  FoodData(
      id: 7,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 8,
      title: "خوخ",
      description: peach_des,
      amountScale: mediumAmount,
      image: peach_image,
      calories: 50,
      protein: 1,
      fat: 0.5,
      carb: 15),
  FoodData(
      id: 9,
      title: "أناناس",
      description: pineapple_des,
      amountScale: gramAmount,
      image: pineapple_image,
      calories: 50,
      protein: 0.5,
      fat: 0.1,
      carb: 13),
  FoodData(
      id: 10,
      title: "فراولة",
      description: strawberry_des,
      amountScale: gramAmount,
      image: strawberry_image,
      calories: 33,
      protein: 0.7,
      fat: 0.3,
      carb: 8),
  FoodData(
      id: 11,
      title: "يوسفي",
      description: mandarin_des,
      amountScale: mediumAmount,
      image: mandarin_image,
      calories: 47,
      protein: 0.7,
      fat: 0.3,
      carb: 11.7),
  FoodData(
      id: 12,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
  FoodData(
      id: 13,
      title: "خس",
      description: lettuce_des,
      amountScale: gramAmount,
      image: lettuce_image,
      calories: 17,
      protein: 1.2,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 14,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 15,
      title: "سلق",
      description: salq_des,
      amountScale: gramAmount,
      image: salq_image,
      calories: 19,
      protein: 1.8,
      fat: 3.7,
      carb: 0.2),
  FoodData(
      id: 16,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 17,
      title: "سمك ماكريل",
      description: makarelFish_des,
      amountScale: gramAmount,
      image: makarelFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 18,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
];
final List<FoodData> insomniaFoodList = [
  FoodData(
      id: 1,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 2,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 3,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 4,
      title: "سمك ماكريل",
      description: makarelFish_des,
      amountScale: gramAmount,
      image: makarelFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 5,
      title: "لحم الديك الرومي",
      description: turkey_des,
      amountScale: gramAmount,
      image: turkey_image,
      calories: 147,
      protein: 30,
      fat: 2.2,
      carb: 0),
  FoodData(
      id: 6,
      title: "أرز أبيض",
      description: whiteRice_des,
      amountScale: gramAmount,
      image: whiteRice_image,
      calories: 360,
      protein: 7,
      fat: 0.6,
      carb: 79),
  FoodData(
      id: 7,
      title: "كيوي",
      description: kiwi_des,
      amountScale: mediumAmount,
      image: kiwi_image,
      calories: 42,
      protein: 0.8,
      fat: 0.4,
      carb: 10),
  FoodData(
      id: 8,
      title: "كرز",
      description: cherry_des,
      amountScale: gramAmount,
      image: cherry_image,
      calories: 50,
      protein: 1,
      fat: 0.3,
      carb: 12),
  FoodData(
      id: 9,
      title: "شوفان",
      description: oats_des,
      amountScale: gramAmount,
      image: oats_image,
      calories: 389,
      protein: 17,
      fat: 7,
      carb: 66.3),
  FoodData(
      id: 10,
      title: "أرز بني",
      description: brownRice_des,
      amountScale: gramAmount,
      image: brownRice_image,
      calories: 370,
      protein: 8,
      fat: 2.9,
      carb: 77),
  FoodData(
      id: 11,
      title: "قرع العسل",
      description: pumpkin_des,
      amountScale: gramAmount,
      image: pumpkin_image,
      calories: 26,
      protein: 1,
      fat: 0.1,
      carb: 6.5),
  FoodData(
      id: 12,
      title: "جوز الهند",
      description: coconut_des,
      amountScale: gramAmount,
      image: coconut_image,
      calories: 354,
      protein: 3.3,
      fat: 33,
      carb: 15),
  FoodData(
      id: 13,
      title: "كرز",
      description: cherry_des,
      amountScale: gramAmount,
      image: cherry_image,
      calories: 50,
      protein: 1,
      fat: 0.3,
      carb: 12),
]; // الارق
final List<FoodData> memoryImproveFoodList = [
  FoodData(
      id: 1,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 2,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 3,
      title: "التوت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 4,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 5,
      title: "قرع العسل",
      description: pumpkin_des,
      amountScale: gramAmount,
      image: pumpkin_image,
      calories: 26,
      protein: 1,
      fat: 0.1,
      carb: 6.5),
  FoodData(
      id: 6,
      title: "شوكولاتة",
      description: chocolate_des,
      amountScale: gramAmount,
      image: chocolate_image,
      calories: 546,
      protein: 4.9,
      fat: 31,
      carb: 61),
  FoodData(
      id: 7,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 8,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 9,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 10,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 11,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 12,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 13,
      title: "بذور الكتان",
      description: kettan_des,
      amountScale: gramAmount,
      image: kettan_image,
      calories: 534,
      protein: 18,
      fat: 42,
      carb: 29),
  FoodData(
      id: 14,
      title: "بذور الشيا",
      description: chia_des,
      amountScale: gramAmount,
      image: chia_image,
      calories: 486,
      protein: 17,
      fat: 31,
      carb: 42),
  FoodData(
      id: 15,
      title: "جبنة توفو",
      description: tofoCheese_des,
      amountScale: gramAmount,
      image: tofoCheese_image,
      calories: 270,
      protein: 18.8,
      fat: 20.2,
      carb: 8.8),
  FoodData(
      id: 16,
      title: "محار البحر",
      description: mahar_des,
      amountScale: gramAmount,
      image: mahar_image,
      calories: 86,
      protein: 12,
      fat: 2.5,
      carb: 4),
  FoodData(
      id: 17,
      title: "زيت الكانولا",
      description: canolaOil_des,
      amountScale: sponAmount,
      image: canolaOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 18,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 19,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
];
final List<FoodData> coldFoodList = [
  FoodData(
      id: 1,
      title: "ثوم",
      description: garlic_des,
      amountScale: gramAmount,
      image: garlic_image,
      calories: 149,
      protein: 6.4,
      fat: 0.5,
      carb: 33),
  FoodData(
      id: 2,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 3,
      title: "ليمون",
      description: lemon_des,
      amountScale: mediumAmount,
      image: lemon_image,
      calories: 17,
      protein: 0.6,
      fat: 0.2,
      carb: 5),
  FoodData(
      id: 4,
      title: "كيوي",
      description: kiwi_des,
      amountScale: mediumAmount,
      image: kiwi_image,
      calories: 42,
      protein: 0.8,
      fat: 0.4,
      carb: 10),
  FoodData(
      id: 5,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 6,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 7,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 8,
      title: "لب سوري",
      description: sunflowerPulp_des,
      amountScale: gramAmount,
      image: sunflowerPulp_image,
      calories: 619,
      protein: 17.2,
      fat: 56.8,
      carb: 20.6),
  FoodData(
      id: 9,
      title: "دقيق القمح",
      description: wheatFlour_des,
      amountScale: gramAmount,
      image: wheatFlour_image,
      calories: 364,
      protein: 10,
      fat: 1,
      carb: 76),
  FoodData(
      id: 10,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 11,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 12,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
  FoodData(
      id: 13,
      title: "لبن رائب",
      description: yoghurt_des,
      amountScale: cupAmount,
      image: yoghurt_image,
      calories: 151,
      protein: 8,
      fat: 8,
      carb: 12),
  FoodData(
      id: 14,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
];
final List<FoodData> indigestionFoodList = [
  FoodData(
      id: 1,
      title: "نعناع",
      description: mint_des,
      amountScale: gramAmount,
      image: mint_image,
      calories: 70,
      protein: 3.7,
      fat: 0.9,
      carb: 14.9),
  FoodData(
      id: 2,
      title: "بابايا",
      description: papaya_des,
      amountScale: gramAmount,
      image: papaya_image,
      calories: 39,
      protein: 0.6,
      fat: 0.1,
      carb: 9.8),
  FoodData(
      id: 3,
      title: "زنجبيل",
      description: ginger_des,
      amountScale: gramAmount,
      image: ginger_image,
      calories: 80,
      protein: 1.8,
      fat: 0.8,
      carb: 18),
  FoodData(
      id: 4,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 5,
      title: "ليمون",
      description: lemon_des,
      amountScale: mediumAmount,
      image: lemon_image,
      calories: 17,
      protein: 0.6,
      fat: 0.2,
      carb: 5),
  FoodData(
      id: 6,
      title: "كيوي",
      description: kiwi_des,
      amountScale: mediumAmount,
      image: kiwi_image,
      calories: 42,
      protein: 0.8,
      fat: 0.4,
      carb: 10),
  FoodData(
      id: 7,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
];
final List<FoodData> osteoporosisFoodList = [
  FoodData(
      id: 1,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 2,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
  FoodData(
      id: 3,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 4,
      title: "جمبري",
      description: shrimp_des,
      amountScale: gramAmount,
      image: shrimp_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 5,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 6,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 7,
      title: "جبنة توفو",
      description: tofoCheese_des,
      amountScale: gramAmount,
      image: tofoCheese_image,
      calories: 270,
      protein: 18.8,
      fat: 20.2,
      carb: 8.8),
  FoodData(
      id: 8,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 9,
      title: "لحم بقري",
      description: beef_des,
      amountScale: gramAmount,
      image: beef_image,
      calories: 217,
      protein: 26.1,
      fat: 11.8,
      carb: 0),
  FoodData(
      id: 10,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 11,
      title: "افخاد الدجاج",
      description: chickenLegs_des,
      amountScale: gramAmount,
      image: chickenLegs_image,
      calories: 209,
      protein: 26,
      fat: 10.9,
      carb: 0),
  FoodData(
      id: 12,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 13,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 14,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 15,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
];
final List<FoodData> nervesesFoodList = [
  FoodData(
      id: 1,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 2,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 3,
      title: "بنجر",
      description: beetroot_des,
      amountScale: gramAmount,
      image: beetroot_image,
      calories: 43,
      protein: 1.6,
      fat: 0.2,
      carb: 9.5),
  FoodData(
      id: 4,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 5,
      title: "أرز بني",
      description: brownRice_des,
      amountScale: gramAmount,
      image: brownRice_image,
      calories: 370,
      protein: 8,
      fat: 2.9,
      carb: 77),
  FoodData(
      id: 6,
      title: "شوفان",
      description: oats_des,
      amountScale: gramAmount,
      image: oats_image,
      calories: 389,
      protein: 17,
      fat: 7,
      carb: 66.3),
  FoodData(
      id: 7,
      title: "فاصوليا الخضراء",
      description: greenBeens_des,
      amountScale: gramAmount,
      image: greenBeens_image,
      calories: 31,
      protein: 1.8,
      fat: 0.2,
      carb: 7),
  FoodData(
      id: 8,
      title: "فول",
      description: fool_des,
      amountScale: gramAmount,
      image: fool_image,
      calories: 341,
      protein: 26.1,
      fat: 1.5,
      carb: 58.3),
  FoodData(
      id: 9,
      title: "حمص",
      description: hummos_des,
      amountScale: gramAmount,
      image: hummos_image,
      calories: 364,
      protein: 19,
      fat: 6,
      carb: 61),
  FoodData(
      id: 10,
      title: "بذور الكتان",
      description: kettan_des,
      amountScale: gramAmount,
      image: kettan_image,
      calories: 534,
      protein: 18,
      fat: 42,
      carb: 29),
  FoodData(
      id: 11,
      title: "بذور الشيا",
      description: chia_des,
      amountScale: gramAmount,
      image: chia_image,
      calories: 486,
      protein: 17,
      fat: 31,
      carb: 42),
  FoodData(
      id: 12,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 13,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 14,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 15,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 16,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 17,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 18,
      title: "لحم بقري",
      description: beef_des,
      amountScale: gramAmount,
      image: beef_image,
      calories: 217,
      protein: 26.1,
      fat: 11.8,
      carb: 0),
  FoodData(
      id: 19,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 20,
      title: "مشروم",
      description: mashroom_des,
      amountScale: gramAmount,
      image: mashroom_image,
      calories: 22,
      protein: 3.1,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 21,
      title: "توت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 22,
      title: "جريب فروت",
      description: grapefruit_des,
      amountScale: mediumAmount,
      image: grapefruit_image,
      calories: 82,
      protein: 1.6,
      fat: 0.3,
      carb: 20.7),
  FoodData(
      id: 23,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 24,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
];
final List<FoodData> skinFoodList = [
  FoodData(
      id: 1,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 2,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 3,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
  FoodData(
      id: 4,
      title: "رمان",
      description: pomegranate_des,
      amountScale: gramAmount,
      image: pomegranate_image,
      calories: 83,
      protein: 1.7,
      fat: 1.1,
      carb: 18.7),
  FoodData(
      id: 5,
      title: "فول الصويا",
      description: soyaFool_des,
      amountScale: gramAmount,
      image: soyaFool_image,
      calories: 471,
      protein: 35.2,
      fat: 25.4,
      carb: 33.5),
  FoodData(
      id: 6,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 7,
      title: "سمك رنجة",
      description: rengaFish_des,
      amountScale: gramAmount,
      image: rengaFish_image,
      calories: 217,
      protein: 25,
      fat: 12,
      carb: 0),
  FoodData(
      id: 8,
      title: "سمك ماكريل",
      description: makarelFish_des,
      amountScale: gramAmount,
      image: makarelFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 9,
      title: "فلفل حلو",
      description: pepper_des,
      amountScale: gramAmount,
      image: pepper_image,
      calories: 40,
      protein: 2,
      fat: 0.2,
      carb: 9),
  FoodData(
      id: 10,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 11,
      title: "زيت الزيتون",
      description: oliveOil_des,
      amountScale: sponAmount,
      image: oliveOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 12,
      title: "جزر",
      description: carrot_des,
      amountScale: gramAmount,
      image: carrot_image,
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carb: 10),
];
final List<FoodData> diabeticsFoodList = [
  FoodData(
      id: 1,
      title: "خس",
      description: lettuce_des,
      amountScale: gramAmount,
      image: lettuce_image,
      calories: 17,
      protein: 1.2,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 2,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 3,
      title: "جرجير",
      description: watercress_des,
      amountScale: gramAmount,
      image: watercress_image,
      calories: 25,
      protein: 2.6,
      fat: 3.6,
      carb: 0.6),
  FoodData(
      id: 4,
      title: "ذرة",
      description: corn_des,
      amountScale: gramAmount,
      image: corn_image,
      calories: 96,
      protein: 3.4,
      fat: 1.5,
      carb: 21),
  FoodData(
      id: 5,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 6,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 7,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
  FoodData(
      id: 8,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 9,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 10,
      title: "سمك دنيس",
      description: denesFish_des,
      amountScale: gramAmount,
      image: denesFish_image,
      calories: 143,
      protein: 23.4,
      fat: 5.3,
      carb: 0),
  FoodData(
      id: 11,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 12,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 13,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 14,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 15,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 16,
      title: "بذور الكتان",
      description: kettan_des,
      amountScale: gramAmount,
      image: kettan_image,
      calories: 534,
      protein: 18,
      fat: 42,
      carb: 29),
  FoodData(
      id: 17,
      title: "بذور الشيا",
      description: chia_des,
      amountScale: gramAmount,
      image: chia_image,
      calories: 486,
      protein: 17,
      fat: 31,
      carb: 42),
  FoodData(
      id: 18,
      title: "زيت الزيتون",
      description: oliveOil_des,
      amountScale: sponAmount,
      image: oliveOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
];
final List<FoodData> stomachFoodList = [
  FoodData(
      id: 1,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
  FoodData(
      id: 2,
      title: "لبن رائب",
      description: yoghurt_des,
      amountScale: cupAmount,
      image: yoghurt_image,
      calories: 151,
      protein: 8,
      fat: 8,
      carb: 12),
  FoodData(
      id: 3,
      title: "نعناع",
      description: mint_des,
      amountScale: gramAmount,
      image: mint_image,
      calories: 70,
      protein: 3.7,
      fat: 0.9,
      carb: 14.9),
  FoodData(
      id: 4,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 5,
      title: "بابايا",
      description: papaya_des,
      amountScale: gramAmount,
      image: papaya_image,
      calories: 39,
      protein: 0.6,
      fat: 0.1,
      carb: 9.8),
  FoodData(
      id: 6,
      title: "خوخ",
      description: peach_des,
      amountScale: mediumAmount,
      image: peach_image,
      calories: 50,
      protein: 1,
      fat: 0.5,
      carb: 15),
  FoodData(
      id: 7,
      title: "خيار",
      description: cucumber_des,
      amountScale: gramAmount,
      image: cucumber_image,
      calories: 15,
      protein: 0.6,
      fat: 0.1,
      carb: 3.6),
  FoodData(
      id: 8,
      title: "أرز أبيض",
      description: whiteRice_des,
      amountScale: gramAmount,
      image: whiteRice_image,
      calories: 360,
      protein: 7,
      fat: 0.6,
      carb: 79),
  FoodData(
      id: 9,
      title: "بذور الكتان",
      description: kettan_des,
      amountScale: gramAmount,
      image: kettan_image,
      calories: 534,
      protein: 18,
      fat: 42,
      carb: 29),
];
