import 'package:food_app/constants.dart';
import 'package:food_app/models/FoodData.dart';
import 'package:food_app/models/description.dart';
import 'package:food_app/models/images_source.dart';

//////////////////////////-- Nuts List --/////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
final List<FoodData> allFoodLists = nutsList +
    meatsList +
    seafoodList +
    oilsList +
    birdsList +
    fruitsList +
    vegetablesList +
    beensList +
    legumesList +
    dairyList +
    bakeryList +
    dessertsList;

final List<FoodData> nutsList = [
  FoodData(
      id: 1,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 2,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 3,
      title: "عين جمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 4,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 5,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 6,
      title: "فول سوداني",
      description: peanut_des,
      amountScale: gramAmount,
      image: peanut_image,
      calories: 567,
      protein: 25.8,
      fat: 49.2,
      carb: 16.1),
  FoodData(
      id: 7,
      title: "لب سوري",
      description: sunflowerPulp_des,
      amountScale: gramAmount,
      image: sunflowerPulp_image,
      calories: 619,
      protein: 17.2,
      fat: 56.8,
      carb: 20.6),
  FoodData(
      id: 8,
      title: "لب ابيض",
      description: whitePulp_des,
      amountScale: gramAmount,
      image: whitePulp_image,
      calories: 600,
      protein: 23.3,
      fat: 46.7,
      carb: 13.3),
  FoodData(
      id: 9,
      title: "لب سوبر",
      description: brownPulp_des,
      amountScale: gramAmount,
      image: brownPulp_image,
      calories: 557,
      protein: 28.3,
      fat: 47.3,
      carb: 15.2)
];

//////////////////////////-- Meat List --//////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
final List<FoodData> meatsList = [
  FoodData(
      id: 1,
      title: "لحم بقري",
      description: beef_des,
      amountScale: gramAmount,
      image: beef_image,
      calories: 217,
      protein: 26.1,
      fat: 11.8,
      carb: 0),
  FoodData(
      id: 2,
      title: "لحم الضأن",
      description: lamb_des,
      amountScale: gramAmount,
      image: lamb_image,
      calories: 258,
      protein: 25.6,
      fat: 16.5,
      carb: 0),
  FoodData(
      id: 3,
      title: "لحم الماعز",
      description: goat_des,
      amountScale: gramAmount,
      image: goat_image,
      calories: 143,
      protein: 27,
      fat: 3,
      carb: 0),
  FoodData(
      id: 4,
      title: "لحم الغنم",
      description: sheep_des,
      amountScale: gramAmount,
      image: sheep_image,
      calories: 283,
      protein: 24.8,
      fat: 19.6,
      carb: 0),
  FoodData(
      id: 5,
      title: "لحم الإبل",
      description: camel_des,
      amountScale: gramAmount,
      image: camel_image,
      calories: 220,
      protein: 26.8,
      fat: 12.1,
      carb: 0),
  FoodData(
      id: 6,
      title: "لحم الأرنب",
      description: bunny_des,
      amountScale: gramAmount,
      image: bunny_image,
      calories: 196,
      protein: 29,
      fat: 8,
      carb: 0),
  FoodData(
      id: 7,
      title: "لانشون",
      description: lanshon_des,
      amountScale: gramAmount,
      image: lanshon_image,
      calories: 189,
      protein: 17.8,
      fat: 11.1,
      carb: 4.4),
  FoodData(
      id: 8,
      title: "بسطرمة",
      description: basterma_des,
      amountScale: gramAmount,
      image: basterma_image,
      calories: 95,
      protein: 19.6,
      fat: 1.1,
      carb: 1.5),
  FoodData(
      id: 9,
      title: "سلامي",
      description: salame_des,
      amountScale: gramAmount,
      image: salame_image,
      calories: 336,
      protein: 22,
      fat: 26,
      carb: 2.4),
  FoodData(
      id: 10,
      title: "سجق",
      description: sausage_des,
      amountScale: gramAmount,
      image: sausage_image,
      calories: 346,
      protein: 14,
      fat: 31,
      carb: 0.7),
  FoodData(
      id: 11,
      title: "سوسيس (نقانق)",
      description: soses_des,
      amountScale: gramAmount,
      image: soses_image,
      calories: 290,
      protein: 10,
      fat: 26,
      carb: 4.2),
  FoodData(
      id: 12,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 13,
      title: "بلوبيف",
      description: blobeef_des,
      amountScale: gramAmount,
      image: blobeef_image,
      calories: 280,
      protein: 27,
      fat: 5.7,
      carb: 20),
  FoodData(
      id: 14,
      title: "لحم مقدد",
      description: dry_meat_des,
      amountScale: gramAmount,
      image: dry_meat_image,
      calories: 198,
      protein: 14.6,
      fat: 14.9,
      carb: 0),
  FoodData(
      id: 15,
      title: "دهن الخروف",
      description: dehn_des,
      amountScale: gramAmount,
      image: dehn_image,
      calories: 361,
      protein: 22,
      fat: 29.6,
      carb: 0),
];

//////////////////// -- Seafood List -- /////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////
final List<FoodData> seafoodList = [
  FoodData(
      id: 1,
      title: "سمك بلطي",
      description: boltiFish_des,
      amountScale: gramAmount,
      image: boltiFish_image,
      calories: 128,
      protein: 26,
      fat: 2.7,
      carb: 0),
  FoodData(
      id: 2,
      title: "سمك بوري",
      description: boriFish_des,
      amountScale: gramAmount,
      image: boriFish_image,
      calories: 206,
      protein: 22,
      fat: 12,
      carb: 0),
  FoodData(
      id: 3,
      title: "سمك بربوني",
      description: barboniFish_des,
      amountScale: gramAmount,
      image: barboniFish_image,
      calories: 110,
      protein: 18.7,
      fat: 3.8,
      carb: 0),
  FoodData(
      id: 4,
      title: "سمك مرجان",
      description: morganFish_des,
      amountScale: gramAmount,
      image: morganFish_image,
      calories: 123,
      protein: 24.5,
      fat: 2.8,
      carb: 0),
  FoodData(
      id: 5,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 6,
      title: "سمك فارس",
      description: farisFish_des,
      amountScale: gramAmount,
      image: farisFish_image,
      calories: 91,
      protein: 21,
      fat: 1,
      carb: 0),
  FoodData(
      id: 7,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 8,
      title: "سمك سيجان",
      description: segalFish_des,
      amountScale: gramAmount,
      image: segalFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 9,
      title: "سمك هامور",
      description: hamorFish_des,
      amountScale: gramAmount,
      image: hamorFish_image,
      calories: 118,
      protein: 25,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 10,
      title: "سمك قاروس",
      description: karosFish_des,
      amountScale: gramAmount,
      image: karosFish_image,
      calories: 97,
      protein: 18,
      fat: 2,
      carb: 0),
  FoodData(
      id: 11,
      title: "سمك دنيس",
      description: denesFish_des,
      amountScale: gramAmount,
      image: denesFish_image,
      calories: 143,
      protein: 23.4,
      fat: 5.3,
      carb: 0),
  FoodData(
      id: 12,
      title: "سمك موسى",
      description: mosaFish_des,
      amountScale: gramAmount,
      image: mosaFish_image,
      calories: 86,
      protein: 15.4,
      fat: 2.3,
      carb: 0),
  FoodData(
      id: 13,
      title: "سمك حريد",
      description: heredFish_des,
      amountScale: gramAmount,
      image: heredFish_image,
      calories: 27,
      protein: 22.1,
      fat: 0.4,
      carb: 0),
  FoodData(
      id: 14,
      title: "سمك وقار",
      description: wakarFish_des,
      amountScale: gramAmount,
      image: wakarFish_image,
      calories: 118,
      protein: 25,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 15,
      title: "سمك بياض",
      description: bayadFish_des,
      amountScale: gramAmount,
      image: bayadFish_image,
      calories: 117,
      protein: 23.5,
      fat: 1.6,
      carb: 0),
  FoodData(
      id: 16,
      title: "سمك قشر بياض",
      description: keshrbayadFish_des,
      amountScale: gramAmount,
      image: keshrbayadFish_image,
      calories: 112,
      protein: 20.1,
      fat: 1.8,
      carb: 0),
  FoodData(
      id: 17,
      title: "سمك قرموط",
      description: karmotFish_des,
      amountScale: gramAmount,
      image: karmotFish_image,
      calories: 105,
      protein: 18,
      fat: 2.9,
      carb: 0),
  FoodData(
      id: 18,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 19,
      title: "سمك رنجة",
      description: rengaFish_des,
      amountScale: gramAmount,
      image: rengaFish_image,
      calories: 217,
      protein: 25,
      fat: 12,
      carb: 0),
  FoodData(
      id: 20,
      title: "سمك مكارونة",
      description: makaronaFish_des,
      amountScale: gramAmount,
      image: makaronaFish_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 0),
  FoodData(
      id: 21,
      title: "سمك ماكريل",
      description: makarelFish_des,
      amountScale: gramAmount,
      image: makarelFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 22,
      title: "سمك ناجل",
      description: nagelFish_des,
      amountScale: gramAmount,
      image: nagelFish_image,
      calories: 118,
      protein: 25,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 23,
      title: "سمك شعور",
      description: shoaorFish_des,
      amountScale: gramAmount,
      image: shoaorFish_image,
      calories: 148,
      protein: 21,
      fat: 6.6,
      carb: 0),
  FoodData(
      id: 24,
      title: "جمبري",
      description: shrimp_des,
      amountScale: gramAmount,
      image: shrimp_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 25,
      title: "كابوريا",
      description: kaborya_des,
      amountScale: gramAmount,
      image: kaborya_image,
      calories: 83,
      protein: 18,
      fat: 0.7,
      carb: 0),
  FoodData(
      id: 26,
      title: "استاكوزا",
      description: estakoza_des,
      amountScale: gramAmount,
      image: estakoza_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 27,
      title: "حبار",
      description: habbar_des,
      amountScale: gramAmount,
      image: habbar_image,
      calories: 92,
      protein: 16,
      fat: 1.4,
      carb: 3.1),
  FoodData(
      id: 28,
      title: "محار البحر",
      description: mahar_des,
      amountScale: gramAmount,
      image: mahar_image,
      calories: 86,
      protein: 12,
      fat: 2.5,
      carb: 4),
];

///////////////////////-- Oils List -- ////////////////////////////////
///////////////////////////////////////////////////////////////////////
final List<FoodData> oilsList = [
  FoodData(
      id: 1,
      title: "زيت الذرة",
      description: cornOil_des,
      amountScale: sponAmount,
      image: cornOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 2,
      title: "زيت النخيل",
      description: palmOil_des,
      amountScale: sponAmount,
      image: palmOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 3,
      title: "زيت الكانولا",
      description: canolaOil_des,
      amountScale: sponAmount,
      image: canolaOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 4,
      title: "زيت الزيتون",
      description: oliveOil_des,
      amountScale: sponAmount,
      image: oliveOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 5,
      title: "زيت جوز الهند",
      description: coconutOil_des,
      amountScale: sponAmount,
      image: coconutOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 6,
      title: "زيت عباد الشمس",
      description: sunflowerOil_des,
      amountScale: sponAmount,
      image: sunflowerOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 7,
      title: "زيت بذرة القطن",
      description: cottonOil_des,
      amountScale: sponAmount,
      image: cottonOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 8,
      title: "زبدة",
      description: butter_des,
      amountScale: sponAmount,
      image: butter_image,
      calories: 102,
      protein: 0,
      fat: 12,
      carb: 0),
  FoodData(
      id: 9,
      title: "سمن",
      description: samn_des,
      amountScale: sponAmount,
      image: samn_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0)
];

final List<FoodData> birdsList = [
  FoodData(
      id: 1,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 2,
      title: "صفار البيض",
      description: eggYork_des,
      amountScale: mediumAmount,
      image: eggYork_image,
      calories: 55,
      protein: 2.7,
      fat: 4.5,
      carb: 0.6),
  FoodData(
      id: 3,
      title: "بياض البيض",
      description: eggWhites_des,
      amountScale: mediumAmount,
      image: eggWhites_image,
      calories: 17,
      protein: 3.6,
      fat: 0.1,
      carb: 0.2),
  FoodData(
      id: 4,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 5,
      title: "افخاد الدجاج",
      description: chickenLegs_des,
      amountScale: gramAmount,
      image: chickenLegs_image,
      calories: 209,
      protein: 26,
      fat: 10.9,
      carb: 0),
  FoodData(
      id: 6,
      title: "لحم البط",
      description: duck_des,
      amountScale: gramAmount,
      image: duck_image,
      calories: 337,
      protein: 19,
      fat: 28,
      carb: 0),
  FoodData(
      id: 7,
      title: "لحم الإوز",
      description: geese_des,
      amountScale: gramAmount,
      image: geese_image,
      calories: 238,
      protein: 29,
      fat: 12.7,
      carb: 0),
  FoodData(
      id: 8,
      title: "لحم الحمام",
      description: pigeon_des,
      amountScale: gramAmount,
      image: pigeon_image,
      calories: 213,
      protein: 24,
      fat: 13,
      carb: 0),
  FoodData(
      id: 9,
      title: "لحم السمان",
      description: quail_des,
      amountScale: gramAmount,
      image: quail_image,
      calories: 227,
      protein: 25.2,
      fat: 14.1,
      carb: 0),
  FoodData(
      id: 10,
      title: "لحم الديك الرومي",
      description: turkey_des,
      amountScale: gramAmount,
      image: turkey_image,
      calories: 147,
      protein: 30,
      fat: 2.2,
      carb: 0),
  FoodData(
      id: 11,
      title: "لحم النعام",
      description: ostrich_des,
      amountScale: gramAmount,
      image: ostrich_image,
      calories: 145,
      protein: 28,
      fat: 2.6,
      carb: 0),
  FoodData(
      id: 12,
      title: "بيض الأوز",
      description: eggGeese_des,
      amountScale: mediumAmount,
      image: eggGeese_image,
      calories: 266,
      protein: 20,
      fat: 19,
      carb: 1.9),
  FoodData(
      id: 13,
      title: "بيض البط",
      description: eggDuck_des,
      amountScale: mediumAmount,
      image: eggDuck_image,
      calories: 130,
      protein: 9,
      fat: 9.6,
      carb: 1),
  FoodData(
      id: 14,
      title: "بيض السمان",
      description: eggQuail_des,
      amountScale: mediumAmount,
      image: eggQuail_image,
      calories: 14,
      protein: 1.2,
      fat: 1,
      carb: 0)
];

///////////////////// -- Fruits List -//////////////////////////////
///////////////////////////////////////////////////////////////////
final List<FoodData> fruitsList = [
  FoodData(
      id: 1,
      title: "تفاح",
      description: apple_des,
      amountScale: mediumAmount,
      image: apple_image,
      calories: 95,
      protein: 0.5,
      fat: 0.3,
      carb: 25),
  FoodData(
      id: 2,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 3,
      title: "اناناس",
      description: pineapple_des,
      amountScale: gramAmount,
      image: pineapple_image,
      calories: 50,
      protein: 0.5,
      fat: 0.1,
      carb: 13),
  FoodData(
      id: 4,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 5,
      title: "توت ازرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 6,
      title: "جوافة",
      description: guava_des,
      amountScale: mediumAmount,
      image: guava_image,
      calories: 38,
      protein: 1.4,
      fat: 0.5,
      carb: 8),
  FoodData(
      id: 7,
      title: "ليمون",
      description: lemon_des,
      amountScale: mediumAmount,
      image: lemon_image,
      calories: 17,
      protein: 0.6,
      fat: 0.2,
      carb: 5),
  FoodData(
      id: 8,
      title: "جوز الهند",
      description: coconut_des,
      amountScale: gramAmount,
      image: coconut_image,
      calories: 354,
      protein: 3.3,
      fat: 33,
      carb: 15),
  FoodData(
      id: 9,
      title: "مانجا",
      description: mango_des,
      amountScale: mediumAmount,
      image: mango_image,
      calories: 201,
      protein: 2.8,
      fat: 1.3,
      carb: 50),
  FoodData(
      id: 10,
      title: "تمر",
      description: dates_des,
      amountScale: mediumAmount,
      image: dates_image,
      calories: 20,
      protein: 0.2,
      fat: 0,
      carb: 5),
  FoodData(
      id: 11,
      title: "قرع العسل",
      description: pumpkin_des,
      amountScale: gramAmount,
      image: pumpkin_image,
      calories: 26,
      protein: 1,
      fat: 0.1,
      carb: 6.5),
  FoodData(
      id: 12,
      title: "توت العليق",
      description: raspberry_des,
      amountScale: gramAmount,
      image: raspberry_image,
      calories: 53,
      protein: 1.2,
      fat: 0.7,
      carb: 12),
  FoodData(
      id: 13,
      title: "يوسفي",
      description: mandarin_des,
      amountScale: mediumAmount,
      image: mandarin_image,
      calories: 47,
      protein: 0.7,
      fat: 0.3,
      carb: 11.7),
  FoodData(
      id: 14,
      title: "برقوق",
      description: plum_des,
      amountScale: mediumAmount,
      image: plum_image,
      calories: 30,
      protein: 0.5,
      fat: 0.2,
      carb: 8),
  FoodData(
      id: 15,
      title: "مشمش",
      description: apricot_des,
      amountScale: mediumAmount,
      image: apricot_image,
      calories: 17,
      protein: 0.5,
      fat: 0.1,
      carb: 3.9),
  FoodData(
      id: 16,
      title: "قشطة",
      description: keshta_des,
      amountScale: gramAmount,
      image: keshta_image,
      calories: 75,
      protein: 1,
      fat: 17,
      carb: 17),
  FoodData(
      id: 17,
      title: "توت بري",
      description: cranberry_des,
      amountScale: gramAmount,
      image: cranberry_image,
      calories: 43,
      protein: 1.4,
      fat: 0.5,
      carb: 10),
  FoodData(
      id: 18,
      title: "تين",
      description: fig_des,
      amountScale: mediumAmount,
      image: fig_image,
      calories: 37,
      protein: 0.38,
      fat: 0.15,
      carb: 9.6),
  FoodData(
      id: 19,
      title: "تين شوكي",
      description: figs_des,
      amountScale: mediumAmount,
      image: figs_image,
      calories: 41,
      protein: 0.7,
      fat: 0.5,
      carb: 9.5),
  FoodData(
      id: 20,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 21,
      title: "كمثرى",
      description: peer_des,
      amountScale: mediumAmount,
      image: peer_image,
      calories: 103,
      protein: 0.7,
      fat: 0.2,
      carb: 27.5),
  FoodData(
      id: 22,
      title: "بطيخ",
      description: watermelon_des,
      amountScale: gramAmount,
      image: watermelon_image,
      calories: 30,
      protein: 0.6,
      fat: 0.2,
      carb: 8),
  FoodData(
      id: 23,
      title: "رمان",
      description: pomegranate_des,
      amountScale: gramAmount,
      image: pomegranate_image,
      calories: 83,
      protein: 1.7,
      fat: 1.1,
      carb: 18.7),
  FoodData(
      id: 24,
      title: "عنب",
      description: grabe_des,
      amountScale: gramAmount,
      image: grabe_image,
      calories: 67,
      protein: 0.6,
      fat: 0.4,
      carb: 17),
  FoodData(
      id: 25,
      title: "نبق",
      description: nabq_des,
      amountScale: gramAmount,
      image: nabq_image,
      calories: 82,
      protein: 1,
      fat: 3,
      carb: 11),
  FoodData(
      id: 26,
      title: "حرنكش",
      description: harankash_des,
      amountScale: gramAmount,
      image: harankash_image,
      calories: 53,
      protein: 1.9,
      fat: 0.7,
      carb: 11),
  FoodData(
      id: 27,
      title: "شمام",
      description: melon_des,
      amountScale: gramAmount,
      image: melon_image,
      calories: 34,
      protein: 0.8,
      fat: 0.2,
      carb: 8),
  FoodData(
      id: 28,
      title: "كرز",
      description: cherry_des,
      amountScale: gramAmount,
      image: cherry_image,
      calories: 50,
      protein: 1,
      fat: 0.3,
      carb: 12),
  FoodData(
      id: 29,
      title: "بابايا",
      description: papaya_des,
      amountScale: gramAmount,
      image: papaya_image,
      calories: 39,
      protein: 0.6,
      fat: 0.1,
      carb: 9.8),
  FoodData(
      id: 30,
      title: "تفاح اخضر",
      description: greenApple_des,
      amountScale: mediumAmount,
      image: greenApple_image,
      calories: 95,
      protein: 0.5,
      fat: 0.3,
      carb: 25),
  FoodData(
      id: 31,
      title: "جريب فروت",
      description: grapefruit_des,
      amountScale: mediumAmount,
      image: grapefruit_image,
      calories: 82,
      protein: 1.6,
      fat: 0.3,
      carb: 20.7),
  FoodData(
      id: 32,
      title: "فراولة",
      description: strawberry_des,
      amountScale: gramAmount,
      image: strawberry_image,
      calories: 33,
      protein: 0.7,
      fat: 0.3,
      carb: 8),
  FoodData(
      id: 33,
      title: "كيوي",
      description: kiwi_des,
      amountScale: mediumAmount,
      image: kiwi_image,
      calories: 42,
      protein: 0.8,
      fat: 0.4,
      carb: 10),
  FoodData(
      id: 34,
      title: "فاكهه التنين",
      description: dragonfruit_des,
      amountScale: mediumAmount,
      image: dragonfruit_image,
      calories: 61,
      protein: 1.1,
      fat: 0.5,
      carb: 15),
  FoodData(
      id: 35,
      title: "زعرور",
      description: hawthorn_des,
      amountScale: gramAmount,
      image: hawthorn_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 36,
      title: "خوخ",
      description: peach_des,
      amountScale: mediumAmount,
      image: peach_image,
      calories: 50,
      protein: 1,
      fat: 0.5,
      carb: 15),
  FoodData(
      id: 37,
      title: "كاكا",
      description: kaka_des,
      amountScale: mediumAmount,
      image: kaka_image,
      calories: 32,
      protein: 0.2,
      fat: 0.1,
      carb: 8),
  FoodData(
      id: 38,
      title: "زبيب",
      description: zebeeb_des,
      amountScale: gramAmount,
      image: zebeeb_image,
      calories: 299,
      protein: 3.1,
      fat: 0.5,
      carb: 79),
  FoodData(
      id: 39,
      title: "قراصيا",
      description: karasya_des,
      amountScale: mediumAmount,
      image: karasya_image,
      calories: 23,
      protein: 0.2,
      fat: 0,
      carb: 6),
];

/////////////////////-- Vegetables List -- /////////////////////////////
///////////////////////////////////////////////////////////////////////
final List<FoodData> vegetablesList = [
  FoodData(
      id: 1,
      title: "بطاطس",
      description: potato_des,
      amountScale: gramAmount,
      image: potato_image,
      calories: 77,
      protein: 2,
      fat: 0.1,
      carb: 17),
  FoodData(
      id: 2,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 3,
      title: "بصل",
      description: onion_des,
      amountScale: gramAmount,
      image: onion_image,
      calories: 40,
      protein: 1.1,
      fat: 0.1,
      carb: 9),
  FoodData(
      id: 4,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 5,
      title: "كوسا",
      description: courgettes_des,
      amountScale: gramAmount,
      image: courgettes_image,
      calories: 21,
      protein: 2.7,
      fat: 0.4,
      carb: 3.1),
  FoodData(
      id: 6,
      title: "جرجير",
      description: watercress_des,
      amountScale: gramAmount,
      image: watercress_image,
      calories: 25,
      protein: 2.6,
      fat: 3.6,
      carb: 0.6),
  FoodData(
      id: 7,
      title: "بنجر",
      description: beetroot_des,
      amountScale: gramAmount,
      image: beetroot_image,
      calories: 43,
      protein: 1.6,
      fat: 0.2,
      carb: 9.5),
  FoodData(
      id: 8,
      title: "ذرة",
      description: corn_des,
      amountScale: gramAmount,
      image: corn_image,
      calories: 96,
      protein: 3.4,
      fat: 1.5,
      carb: 21),
  FoodData(
      id: 9,
      title: "ورق العنب",
      description: grapeLeaves_des,
      amountScale: gramAmount,
      image: grapeLeaves_image,
      calories: 93,
      protein: 6,
      fat: 2.1,
      carb: 17),
  FoodData(
      id: 10,
      title: "فاصوليا الخضراء",
      description: greenBeens_des,
      amountScale: gramAmount,
      image: greenBeens_image,
      calories: 31,
      protein: 1.8,
      fat: 0.2,
      carb: 7),
  FoodData(
      id: 11,
      title: "لوبيا الخضراء",
      description: lubya_des,
      amountScale: gramAmount,
      image: lubya_image,
      calories: 336,
      protein: 24,
      fat: 1.3,
      carb: 60),
  FoodData(
      id: 12,
      title: "جزر",
      description: carrot_des,
      amountScale: gramAmount,
      image: carrot_image,
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carb: 10),
  FoodData(
      id: 13,
      title: "خيار",
      description: cucumber_des,
      amountScale: gramAmount,
      image: cucumber_image,
      calories: 15,
      protein: 0.6,
      fat: 0.1,
      carb: 3.6),
  FoodData(
      id: 14,
      title: "بقدونس",
      description: parsley_des,
      amountScale: gramAmount,
      image: parsley_image,
      calories: 36,
      protein: 3,
      fat: 0.8,
      carb: 6.3),
  FoodData(
      id: 15,
      title: "شبت",
      description: dill_des,
      amountScale: gramAmount,
      image: dill_image,
      calories: 43,
      protein: 3.5,
      fat: 1.1,
      carb: 7),
  FoodData(
      id: 16,
      title: "طماطم",
      description: tomato_des,
      amountScale: gramAmount,
      image: tomato_image,
      calories: 18,
      protein: 0.9,
      fat: 0.2,
      carb: 3.9),
  FoodData(
      id: 17,
      title: "باذنجان",
      description: eggplant_des,
      amountScale: gramAmount,
      image: eggplant_image,
      calories: 24,
      protein: 1,
      fat: 0.2,
      carb: 5.7),
  FoodData(
      id: 18,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 19,
      title: "ريحان",
      description: basil_des,
      amountScale: gramAmount,
      image: basil_image,
      calories: 23,
      protein: 3.1,
      fat: 0.6,
      carb: 2.6),
  FoodData(
      id: 20,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
  FoodData(
      id: 21,
      title: "زيتون",
      description: olive_des,
      amountScale: gramAmount,
      image: olive_image,
      calories: 115,
      protein: 0.8,
      fat: 11,
      carb: 6),
  FoodData(
      id: 22,
      title: "سلق",
      description: salq_des,
      amountScale: gramAmount,
      image: salq_image,
      calories: 19,
      protein: 1.8,
      fat: 3.7,
      carb: 0.2),
  FoodData(
      id: 23,
      title: "بازلاء",
      description: chickpea_des,
      amountScale: gramAmount,
      image: chickpea_image,
      calories: 81,
      protein: 5,
      fat: 0.4,
      carb: 14),
  FoodData(
      id: 24,
      title: "كزبرة",
      description: coriander_des,
      amountScale: gramAmount,
      image: coriander_image,
      calories: 23,
      protein: 2.1,
      fat: 0.5,
      carb: 3.7),
  FoodData(
      id: 25,
      title: "نعناع",
      description: mint_des,
      amountScale: gramAmount,
      image: mint_image,
      calories: 70,
      protein: 3.7,
      fat: 0.9,
      carb: 14.9),
  FoodData(
      id: 26,
      title: "فلفل حار",
      description: chilli_des,
      amountScale: gramAmount,
      image: chilli_image,
      calories: 40,
      protein: 1.9,
      fat: 0.4,
      carb: 9),
  FoodData(
      id: 27,
      title: "فلفل حلو",
      description: pepper_des,
      amountScale: gramAmount,
      image: pepper_image,
      calories: 40,
      protein: 2,
      fat: 0.2,
      carb: 9),
  FoodData(
      id: 28,
      title: "قلقاس",
      description: taro_des,
      amountScale: gramAmount,
      image: taro_image,
      calories: 112,
      protein: 1.5,
      fat: 0.2,
      carb: 26.5),
  FoodData(
      id: 29,
      title: "خس",
      description: lettuce_des,
      amountScale: gramAmount,
      image: lettuce_image,
      calories: 17,
      protein: 1.2,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 30,
      title: "قرنبيط",
      description: qarnabeet_des,
      amountScale: gramAmount,
      image: qarnabeet_image,
      calories: 25,
      protein: 1.9,
      fat: 0.3,
      carb: 5),
  FoodData(
      id: 31,
      title: "مشروم",
      description: mashroom_des,
      amountScale: gramAmount,
      image: mashroom_image,
      calories: 22,
      protein: 3.1,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 32,
      title: "باميا",
      description: okra_des,
      amountScale: gramAmount,
      image: okra_image,
      calories: 33,
      protein: 1.9,
      fat: 0.2,
      carb: 7),
  FoodData(
      id: 33,
      title: "ملوخية",
      description: molokhiya_des,
      amountScale: gramAmount,
      image: molokhiya_image,
      calories: 37,
      protein: 3.7,
      fat: 0.2,
      carb: 7.3),
  FoodData(
      id: 34,
      title: "ثوم",
      description: garlic_des,
      amountScale: gramAmount,
      image: garlic_image,
      calories: 149,
      protein: 6.4,
      fat: 0.5,
      carb: 33),
  FoodData(
      id: 34,
      title: "زنجبيل",
      description: ginger_des,
      amountScale: gramAmount,
      image: ginger_image,
      calories: 80,
      protein: 1.8,
      fat: 0.8,
      carb: 18),
];

////////////////////////// -- Beens list -- //////////////////////
///////////////////////////////////////////////////////////////////
final List<FoodData> beensList = [
  FoodData(
      id: 1,
      title: "أرز أبيض",
      description: whiteRice_des,
      amountScale: gramAmount,
      image: whiteRice_image,
      calories: 360,
      protein: 7,
      fat: 0.6,
      carb: 79),
  FoodData(
      id: 2,
      title: "أرز أبيض, مطبوخ",
      description: whiteRiceCooked_des,
      amountScale: gramAmount,
      image: whiteRiceCooked_image,
      calories: 130,
      protein: 2.4,
      fat: 0.2,
      carb: 29),
  FoodData(
      id: 3,
      title: "أرز بني",
      description: brownRice_des,
      amountScale: gramAmount,
      image: brownRice_image,
      calories: 370,
      protein: 8,
      fat: 2.9,
      carb: 77),
  FoodData(
      id: 4,
      title: "أرز بني, مطبوخ",
      description: brownRiceCooked_des,
      amountScale: gramAmount,
      image: brownRiceCooked_image,
      calories: 111,
      protein: 2.6,
      fat: 0.9,
      carb: 23),
  FoodData(
      id: 5,
      title: "أرز بسمتي",
      description: basmatiRice_des,
      amountScale: gramAmount,
      image: basmatiRice_image,
      calories: 374,
      protein: 8.1,
      fat: 1,
      carb: 80.4),
  FoodData(
      id: 6,
      title: "أرز بسمتي, مطبوخ",
      description: basmatiRiceCooked_des,
      amountScale: gramAmount,
      image: basmatiRiceCooked_image,
      calories: 123,
      protein: 2.9,
      fat: 0.4,
      carb: 26),
  FoodData(
      id: 7,
      title: "شوفان",
      description: oats_des,
      amountScale: gramAmount,
      image: oats_image,
      calories: 375,
      protein: 13,
      fat: 7,
      carb: 67),
  FoodData(
      id: 8,
      title: "معكرونة",
      description: pasta_des,
      amountScale: gramAmount,
      image: pasta_image,
      calories: 371,
      protein: 13,
      fat: 1.5,
      carb: 75),
  FoodData(
      id: 9,
      title: "دقيق القمح",
      description: wheatFlour_des,
      amountScale: gramAmount,
      image: wheatFlour_image,
      calories: 364,
      protein: 10,
      fat: 1,
      carb: 76),
  FoodData(
      id: 10,
      title: "حبات الذرة",
      description: beadsCorn_des,
      amountScale: gramAmount,
      image: beadsCorn_image,
      calories: 132,
      protein: 3.4,
      fat: 0.8,
      carb: 28),
  FoodData(
      id: 11,
      title: "فريك",
      description: ferek_des,
      amountScale: gramAmount,
      image: ferek_image,
      calories: 325,
      protein: 12.5,
      fat: 4.5,
      carb: 60),
  FoodData(
      id: 12,
      title: "برغل",
      description: grit_des,
      amountScale: gramAmount,
      image: grit_image,
      calories: 342,
      protein: 12.3,
      fat: 1.3,
      carb: 75.9),
  FoodData(
      id: 13,
      title: "شعير",
      description: barley_des,
      amountScale: gramAmount,
      image: barley_image,
      calories: 354,
      protein: 12,
      fat: 2.3,
      carb: 73),
  FoodData(
      id: 14,
      title: "كسكسي",
      description: couscous_des,
      amountScale: gramAmount,
      image: couscous_image,
      calories: 376,
      protein: 12.8,
      fat: 0.6,
      carb: 77.4),
  FoodData(
      id: 15,
      title: "سميد",
      description: semed_des,
      amountScale: gramAmount,
      image: semed_image,
      calories: 360,
      protein: 12.7,
      fat: 1,
      carb: 72.8),
  FoodData(
      id: 16,
      title: "نشا الذرة",
      description: cornStarch_des,
      amountScale: gramAmount,
      image: cornStarch_image,
      calories: 381,
      protein: 0.3,
      fat: 0,
      carb: 91),
  FoodData(
      id: 17,
      title: "بذور الكتان",
      description: kettan_des,
      amountScale: gramAmount,
      image: kettan_image,
      calories: 534,
      protein: 18,
      fat: 42,
      carb: 29),
  FoodData(
      id: 18,
      title: "بذور الشيا",
      description: chia_des,
      amountScale: gramAmount,
      image: chia_image,
      calories: 486,
      protein: 17,
      fat: 31,
      carb: 42),
  FoodData(
      id: 19,
      title: "سمسم",
      description: semsem_des,
      amountScale: gramAmount,
      image: semsem_image,
      calories: 573,
      protein: 18,
      fat: 50,
      carb: 23),
  FoodData(
      id: 20,
      title: "كينوا",
      description: kenwa_des,
      amountScale: gramAmount,
      image: kenwa_image,
      calories: 378,
      protein: 13.3,
      fat: 5.5,
      carb: 64.4),
  FoodData(
      id: 21,
      title: "فشار",
      description: popcorn_des,
      amountScale: gramAmount,
      image: popcorn_image,
      calories: 375,
      protein: 11,
      fat: 4.3,
      carb: 74),
];
///////////////////// -- Legumes List -- ///////////////////////
///////////////////////////////////////////////////////////////
final List<FoodData> legumesList = [
  FoodData(
      id: 1,
      title: "حمص",
      description: hummos_des,
      amountScale: gramAmount,
      image: hummos_image,
      calories: 364,
      protein: 19,
      fat: 6,
      carb: 61),
  FoodData(
      id: 2,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 3,
      title: "عدس ابو جبه",
      description: lentilBegebba_des,
      amountScale: gramAmount,
      image: lentilBegebba_image,
      calories: 358,
      protein: 26,
      fat: 1,
      carb: 62),
  FoodData(
      id: 4,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 5,
      title: "بازلاء",
      description: besella_des,
      amountScale: gramAmount,
      image: besella_image,
      calories: 341,
      protein: 24.5,
      fat: 1.1,
      carb: 60.3),
  FoodData(
      id: 6,
      title: "فول",
      description: fool_des,
      amountScale: gramAmount,
      image: fool_image,
      calories: 341,
      protein: 26.1,
      fat: 1.5,
      carb: 58.3),
  FoodData(
      id: 7,
      title: "فلافل",
      description: falafel_des,
      amountScale: gramAmount,
      image: falafel_image,
      calories: 333,
      protein: 13.3,
      fat: 17.8,
      carb: 31.8),
  FoodData(
      id: 8,
      title: "فول الصويا",
      description: soyaFool_des,
      amountScale: gramAmount,
      image: soyaFool_image,
      calories: 471,
      protein: 35.2,
      fat: 25.4,
      carb: 33.5),
  FoodData(
      id: 9,
      title: "ترمس",
      description: termes_des,
      amountScale: gramAmount,
      image: termes_image,
      calories: 371,
      protein: 36.1,
      fat: 9.7,
      carb: 40.4),
  FoodData(
      id: 10,
      title: "لوبيا بيضاء",
      description: whiteLubya_des,
      amountScale: gramAmount,
      image: whiteLubya_image,
      calories: 336,
      protein: 23.5,
      fat: 1.3,
      carb: 60),
];

///////////////////// -- Dairy List -- ///////////////////////
///////////////////////////////////////////////////////////////
final List<FoodData> dairyList = [
  FoodData(
      id: 1,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
  FoodData(
      id: 2,
      title: "جبنة باراميزان",
      description: baramezanCheese_des,
      amountScale: gramAmount,
      image: baramezanCheese_image,
      calories: 431,
      protein: 38.4,
      fat: 28.6,
      carb: 4),
  FoodData(
      id: 3,
      title: "جبنة حلوم",
      description: halomCheese_des,
      amountScale: gramAmount,
      image: halomCheese_image,
      calories: 393,
      protein: 25,
      fat: 32.1,
      carb: 3.6),
  FoodData(
      id: 4,
      title: "جبنة ريكوتا",
      description: rekotaCheese_des,
      amountScale: gramAmount,
      image: rekotaCheese_image,
      calories: 428,
      protein: 28,
      fat: 32,
      carb: 7),
  FoodData(
      id: 5,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 6,
      title: "جبنة كريم",
      description: creemCheese_des,
      amountScale: gramAmount,
      image: creemCheese_image,
      calories: 342,
      protein: 6,
      fat: 34,
      carb: 4.1),
  FoodData(
      id: 7,
      title: "جبنة موتزاريلا",
      description: mozarellaCheese_des,
      amountScale: gramAmount,
      image: mozarellaCheese_image,
      calories: 280,
      protein: 28,
      fat: 17,
      carb: 3.1),
  FoodData(
      id: 8,
      title: "جبنة براميلي",
      description: barameleCheese_des,
      amountScale: gramAmount,
      image: barameleCheese_image,
      calories: 250,
      protein: 14.3,
      fat: 21.4,
      carb: 0),
  FoodData(
      id: 9,
      title: "جبنة ريكفورد",
      description: rekfordCheese_des,
      amountScale: gramAmount,
      image: rekfordCheese_image,
      calories: 369,
      protein: 22,
      fat: 31,
      carb: 2),
  FoodData(
      id: 10,
      title: "جبنة سويسرية",
      description: swissCheese_des,
      amountScale: gramAmount,
      image: swissCheese_image,
      calories: 380,
      protein: 27,
      fat: 27.8,
      carb: 5.4),
  FoodData(
      id: 11,
      title: "جبنة قديمة",
      description: oldCheese_des,
      amountScale: gramAmount,
      image: oldCheese_image,
      calories: 250,
      protein: 14.5,
      fat: 21.4,
      carb: 0),
  FoodData(
      id: 12,
      title: "جبنة قريش",
      description: kareeshCheese_des,
      amountScale: gramAmount,
      image: kareeshCheese_image,
      calories: 81,
      protein: 10.4,
      fat: 2.3,
      carb: 4.7),
  FoodData(
      id: 13,
      title: "جبنة رومي",
      description: romyCheese_des,
      amountScale: gramAmount,
      image: romyCheese_image,
      calories: 380,
      protein: 23,
      fat: 30,
      carb: 1),
  FoodData(
      id: 14,
      title: "جبنة توفو",
      description: tofoCheese_des,
      amountScale: gramAmount,
      image: tofoCheese_image,
      calories: 270,
      protein: 18.8,
      fat: 20.2,
      carb: 8.8),
  FoodData(
      id: 15,
      title: "جبنة فلمنك",
      description: falamankCheese_des,
      amountScale: gramAmount,
      image: falamankCheese_image,
      calories: 357,
      protein: 25,
      fat: 28,
      carb: 1.4),
  FoodData(
      id: 16,
      title: "جبنة كوارك",
      description: kwarikCheese_des,
      amountScale: gramAmount,
      image: kwarikCheese_image,
      calories: 260,
      protein: 15,
      fat: 22,
      carb: 0),
  FoodData(
      id: 17,
      title: "جبنة عكاوي",
      description: akawiCheese_des,
      amountScale: gramAmount,
      image: akawiCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 18,
      title: "لبنة",
      description: labnaCheese_des,
      amountScale: gramAmount,
      image: labnaCheese_image,
      calories: 59,
      protein: 10,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 19,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 20,
      title: "حليب الإبل",
      description: camelMilk_des,
      amountScale: cupAmount,
      image: camelMilk_image,
      calories: 125,
      protein: 6.3,
      fat: 6.2,
      carb: 12),
  FoodData(
      id: 21,
      title: "حليب الغنم",
      description: sheepMilk_des,
      amountScale: cupAmount,
      image: sheepMilk_image,
      calories: 264,
      protein: 15,
      fat: 17,
      carb: 13),
  FoodData(
      id: 22,
      title: "حليب الماعز",
      description: goatMilk_des,
      amountScale: cupAmount,
      image: goatMilk_image,
      calories: 169,
      protein: 9,
      fat: 10,
      carb: 11),
  FoodData(
      id: 23,
      title: "لبن رائب",
      description: yoghurt_des,
      amountScale: cupAmount,
      image: yoghurt_image,
      calories: 151,
      protein: 8,
      fat: 8,
      carb: 12),
  FoodData(
      id: 24,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
  FoodData(
      id: 24,
      title: "قشده",
      description: kegda_des,
      amountScale: gramAmount,
      image: kegda_image,
      calories: 196,
      protein: 2.7,
      fat: 19,
      carb: 3.7),
];

final List<FoodData> bakeryList = [
  FoodData(
      id: 1,
      title: "خبز بلدي مصري",
      description: egyptionBread_des,
      amountScale: mediumAmount,
      image: egyptionBread_image,
      calories: 300,
      protein: 9.5,
      fat: 4.3,
      carb: 56),
  FoodData(
      id: 2,
      title: "خبز أبيض",
      description: whiteBread_des,
      amountScale: mediumAmount,
      image: whiteBread_image,
      calories: 266,
      protein: 9.8,
      fat: 2.6,
      carb: 55),
  FoodData(
      id: 3,
      title: "خبز فينو",
      description: fenoBread_des,
      amountScale: mediumAmount,
      image: fenoBread_image,
      calories: 244,
      protein: 5.8,
      fat: 7.4,
      carb: 38.2),
  FoodData(
      id: 4,
      title: "خبز فرنسي",
      description: frenchBread_des,
      amountScale: mediumAmount,
      image: frenchBread_image,
      calories: 319,
      protein: 13,
      fat: 2.1,
      carb: 61.9),
  FoodData(
      id: 5,
      title: "خبز كايزر",
      description: kayzarBread_des,
      amountScale: mediumAmount,
      image: kayzarBread_image,
      calories: 180,
      protein: 6,
      fat: 2,
      carb: 38),
  FoodData(
      id: 6,
      title: "خبز نخالة",
      description: nokhalaBread_des,
      amountScale: mediumAmount,
      image: nokhalaBread_image,
      calories: 313,
      protein: 13,
      fat: 4.3,
      carb: 56),
  FoodData(
      id: 27,
      title: "خبز توست",
      description: tost_bread_des,
      amountScale: mediumAmount,
      image: tost_bread_image,
      calories: 75,
      protein: 3.1,
      fat: 1,
      carb: 13),
  FoodData(
      id: 7,
      title: "تميس",
      description: tamees_des,
      amountScale: mediumAmount,
      image: tamees_image,
      calories: 386,
      protein: 12,
      fat: 9,
      carb: 62),
  FoodData(
      id: 8,
      title: "كرواسون بالزبدة",
      description: korwasonBudder_des,
      amountScale: mediumAmount,
      image: korwasonBudder_image,
      calories: 231,
      protein: 4.7,
      fat: 12,
      carb: 26),
  FoodData(
      id: 9,
      title: "كرواسون بالجبنة",
      description: korwasonCheese_des,
      amountScale: mediumAmount,
      image: korwasonCheese_image,
      calories: 235,
      protein: 5.3,
      fat: 11.9,
      carb: 26.8),
  FoodData(
      id: 10,
      title: "دونات",
      description: donut_des,
      amountScale: mediumAmount,
      image: donut_image,
      calories: 270,
      protein: 4,
      fat: 15,
      carb: 31),
  FoodData(
      id: 11,
      title: "سينابون",
      description: cinnabon_des,
      amountScale: mediumAmount,
      image: cinnabon_image,
      calories: 880,
      protein: 12,
      fat: 37,
      carb: 129),
  FoodData(
      id: 12,
      title: "مافن",
      description: mafin_des,
      amountScale: mediumAmount,
      image: mafin_image,
      calories: 203,
      protein: 8.8,
      fat: 2.1,
      carb: 40.4),
  FoodData(
      id: 13,
      title: "بان كيك",
      description: pancake_des,
      amountScale: mediumAmount,
      image: pancake_image,
      calories: 227,
      protein: 6.4,
      fat: 9.7,
      carb: 28.3),
  FoodData(
      id: 14,
      title: "بقسماط",
      description: poksomat_des,
      amountScale: mediumAmount,
      image: poksomat_image,
      calories: 41,
      protein: 1.4,
      fat: 0.7,
      carb: 7),
  FoodData(
      id: 15,
      title: "كوكيز",
      description: cookies_des,
      amountScale: mediumAmount,
      image: cookies_image,
      calories: 40,
      protein: 0.5,
      fat: 1.9,
      carb: 5),
  FoodData(
      id: 16,
      title: "شريحة بيتزا بالجبنة",
      description: pitzaCheese_des,
      amountScale: mediumAmount,
      image: pitzaCheese_image,
      calories: 289,
      protein: 13,
      fat: 11,
      carb: 35),
  FoodData(
      id: 17,
      title: "فطير مشلتت",
      description: feteer_des,
      amountScale: mediumAmount,
      image: feteer_image,
      calories: 339,
      protein: 6.5,
      fat: 8,
      carb: 47.7),
  FoodData(
      id: 18,
      title: "باتيه",
      description: bati_des,
      amountScale: mediumAmount,
      image: bati_image,
      calories: 160,
      protein: 6,
      fat: 7,
      carb: 18),
  FoodData(
      id: 19,
      title: "معمول بالتمر",
      description: maamool_des,
      amountScale: mediumAmount,
      image: maamool_image,
      calories: 90,
      protein: 1,
      fat: 4,
      carb: 12),
  FoodData(
      id: 20,
      title: "سابليه",
      description: sable_des,
      amountScale: mediumAmount,
      image: sable_image,
      calories: 301,
      protein: 3.5,
      fat: 19.5,
      carb: 28),
  FoodData(
      id: 21,
      title: "باتون ساليه",
      description: batonsale_des,
      amountScale: gramAmount,
      image: batonsale_image,
      calories: 426,
      protein: 11.4,
      fat: 5.3,
      carb: 64),
  FoodData(
      id: 22,
      title: "بسكويت نشادر",
      description: biscets_des,
      amountScale: mediumAmount,
      image: biscets_image,
      calories: 251,
      protein: 4.6,
      fat: 12.7,
      carb: 30.3),
  FoodData(
      id: 23,
      title: "كحك سادة",
      description: kahk_des,
      amountScale: mediumAmount,
      image: kahk_image,
      calories: 200,
      protein: 2.1,
      fat: 8.5,
      carb: 27),
  FoodData(
      id: 24,
      title: "كحك بالعجوة",
      description: kahkDates_des,
      amountScale: mediumAmount,
      image: kahkDates_image,
      calories: 220,
      protein: 2.4,
      fat: 8.5,
      carb: 28),
  FoodData(
      id: 25,
      title: "بيتيفور",
      description: betifor_des,
      amountScale: mediumAmount,
      image: betifor_image,
      calories: 100,
      protein: 1,
      fat: 4,
      carb: 11),
  FoodData(
      id: 26,
      title: "سمبوسة",
      description: sambosa_des,
      amountScale: mediumAmount,
      image: sambosa_image,
      calories: 115,
      protein: 10,
      fat: 38,
      carb: 5),
];

final List<FoodData> dessertsList = [
  FoodData(
      id: 1,
      title: "بسبوسة",
      description: basbosa_des,
      amountScale: mediumAmount,
      image: basbosa_image,
      calories: 220,
      protein: 4.1,
      fat: 8.4,
      carb: 32.7),
  FoodData(
      id: 2,
      title: "كنافة",
      description: konafa_des,
      amountScale: mediumAmount,
      image: konafa_image,
      calories: 258,
      protein: 11.2,
      fat: 9.3,
      carb: 42.4),
  FoodData(
      id: 3,
      title: "قطايف",
      description: kataef_des,
      amountScale: mediumAmount,
      image: kataef_image,
      calories: 145,
      protein: 3,
      fat: 4,
      carb: 26),
  FoodData(
      id: 4,
      title: "أصابع زينب",
      description: zenb_des,
      amountScale: mediumAmount,
      image: zenb_image,
      calories: 43,
      protein: 1,
      fat: 2,
      carb: 5.6),
  FoodData(
      id: 5,
      title: "رموش الست",
      description: remoshElset_des,
      amountScale: mediumAmount,
      image: remoshElset_image,
      calories: 171,
      protein: 1.4,
      fat: 8.7,
      carb: 22.7),
  FoodData(
      id: 6,
      title: "بقلاوة",
      description: baklawa_des,
      amountScale: gramAmount,
      image: baklawa_image,
      calories: 540,
      protein: 3,
      fat: 8,
      carb: 16),
  FoodData(
      id: 7,
      title: "سكر",
      description: sugar_des,
      amountScale: sponAmount,
      image: sugar_image,
      calories: 60,
      protein: 0,
      fat: 0,
      carb: 16),
  FoodData(
      id: 8,
      title: "بلح الشام",
      description: balahElsham_des,
      amountScale: gramAmount,
      image: balahElsham_image,
      calories: 420,
      protein: 2,
      fat: 6,
      carb: 14),
  FoodData(
      id: 9,
      title: "جلاش",
      description: gollash_des,
      amountScale: mediumAmount,
      image: gollash_image,
      calories: 168,
      protein: 4,
      fat: 2,
      carb: 35),
  FoodData(
      id: 10,
      title: "ام علي",
      description: omAli_des,
      amountScale: gramAmount,
      image: omAli_image,
      calories: 167,
      protein: 4,
      fat: 7,
      carb: 22),
  FoodData(
      id: 11,
      title: "كريم كراميل",
      description: keremKaramel_des,
      amountScale: gramAmount,
      image: keremKaramel_image,
      calories: 142,
      protein: 4.4,
      fat: 4,
      carb: 23),
  FoodData(
      id: 12,
      title: "كاسترد",
      description: kaster_des,
      amountScale: gramAmount,
      image: kaster_image,
      calories: 122,
      protein: 4,
      fat: 4,
      carb: 18),
  FoodData(
      id: 13,
      title: "لقمة القاضي",
      description: lokmetElkadi_des,
      amountScale: mediumAmount,
      image: lokmetElkadi_image,
      calories: 52,
      protein: 0.3,
      fat: 3,
      carb: 6),
  FoodData(
      id: 14,
      title: "رز بلبن",
      description: rozBelaban_des,
      amountScale: gramAmount,
      image: rozBelaban_image,
      calories: 111,
      protein: 3.3,
      fat: 1.6,
      carb: 21),
  FoodData(
      id: 15,
      title: "شوكولاتة",
      description: chocolate_des,
      amountScale: gramAmount,
      image: chocolate_image,
      calories: 546,
      protein: 4.9,
      fat: 31,
      carb: 61),
  FoodData(
      id: 16,
      title: "عسل",
      description: honey_des,
      amountScale: sponAmount,
      image: honey_image,
      calories: 64,
      protein: 0,
      fat: 0,
      carb: 16),
];
