import 'package:food_app/constants.dart';
import 'package:food_app/models/FoodData.dart';
import 'package:food_app/models/description.dart';
import 'package:food_app/models/food_categories_lists.dart';
import 'package:food_app/models/images_source.dart';

final List<FoodData> carbFoodList = [
  FoodData(
      id: 1,
      title: "شوفان",
      description: oats_des,
      amountScale: gramAmount,
      image: oats_image,
      calories: 389,
      protein: 17,
      fat: 7,
      carb: 66.3),
  FoodData(
      id: 2,
      title: "بطاطس",
      description: potato_des,
      amountScale: gramAmount,
      image: potato_image,
      calories: 77,
      protein: 2,
      fat: 0.1,
      carb: 17),
  FoodData(
      id: 3,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 4,
      title: "أرز أبيض",
      description: whiteRice_des,
      amountScale: gramAmount,
      image: whiteRice_image,
      calories: 360,
      protein: 7,
      fat: 0.6,
      carb: 79),
  FoodData(
      id: 5,
      title: "أرز بسمتي",
      description: basmatiRice_des,
      amountScale: gramAmount,
      image: basmatiRice_image,
      calories: 374,
      protein: 8.1,
      fat: 1,
      carb: 80.4),
  FoodData(
      id: 6,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 7,
      title: "مانجا",
      description: mango_des,
      amountScale: mediumAmount,
      image: mango_image,
      calories: 201,
      protein: 2.8,
      fat: 1.3,
      carb: 50),
  FoodData(
      id: 8,
      title: "خبز بلدي مصري",
      description: egyptionBread_des,
      amountScale: mediumAmount,
      image: egyptionBread_image,
      calories: 300,
      protein: 9.5,
      fat: 4.3,
      carb: 56),
  FoodData(
      id: 9,
      title: "خبز أبيض",
      description: whiteBread_des,
      amountScale: mediumAmount,
      image: whiteBread_image,
      calories: 266,
      protein: 9.8,
      fat: 2.6,
      carb: 55),
  FoodData(
      id: 10,
      title: "خبز فينو",
      description: fenoBread_des,
      amountScale: mediumAmount,
      image: fenoBread_image,
      calories: 244,
      protein: 5.8,
      fat: 7.4,
      carb: 38.2),
  FoodData(
      id: 11,
      title: "خبز فرنسي",
      description: frenchBread_des,
      amountScale: mediumAmount,
      image: frenchBread_image,
      calories: 319,
      protein: 13,
      fat: 2.1,
      carb: 61.9),
  FoodData(
      id: 12,
      title: "تميس",
      description: tamees_des,
      amountScale: mediumAmount,
      image: tamees_image,
      calories: 386,
      protein: 12,
      fat: 9,
      carb: 62),
  FoodData(
      id: 13,
      title: "فطير مشلتت",
      description: feteer_des,
      amountScale: mediumAmount,
      image: feteer_image,
      calories: 339,
      protein: 6.5,
      fat: 8,
      carb: 47.7),
  FoodData(
      id: 14,
      title: "حمص",
      description: hummos_des,
      amountScale: gramAmount,
      image: hummos_image,
      calories: 364,
      protein: 19,
      fat: 6,
      carb: 61),
  FoodData(
      id: 15,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 16,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 17,
      title: "بازلاء",
      description: besella_des,
      amountScale: gramAmount,
      image: besella_image,
      calories: 341,
      protein: 24.5,
      fat: 1.1,
      carb: 60.3),
  FoodData(
      id: 18,
      title: "فول",
      description: fool_des,
      amountScale: gramAmount,
      image: fool_image,
      calories: 341,
      protein: 26.1,
      fat: 1.5,
      carb: 58.3),
  FoodData(
      id: 19,
      title: "لوبيا بيضاء",
      description: whiteLubya_des,
      amountScale: gramAmount,
      image: whiteLubya_image,
      calories: 336,
      protein: 23.5,
      fat: 1.3,
      carb: 60),
  FoodData(
      id: 20,
      title: "كينوا",
      description: kenwa_des,
      amountScale: gramAmount,
      image: kenwa_image,
      calories: 378,
      protein: 13.3,
      fat: 5.5,
      carb: 64.4),
];
final List<FoodData> proteinFoodList = [
  FoodData(
      id: 1,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 2,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 3,
      title: "بياض البيض",
      description: eggWhites_des,
      amountScale: mediumAmount,
      image: eggWhites_image,
      calories: 17,
      protein: 3.6,
      fat: 0.1,
      carb: 0.2),
  FoodData(
      id: 4,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 5,
      title: "زبادي",
      description: yogurt_des,
      amountScale: gramAmount,
      image: yogurt_image,
      calories: 72,
      protein: 5,
      fat: 3,
      carb: 6.3),
  FoodData(
      id: 6,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 7,
      title: "جبنة رومي",
      description: romyCheese_des,
      amountScale: gramAmount,
      image: romyCheese_image,
      calories: 380,
      protein: 23,
      fat: 30,
      carb: 1),
  FoodData(
      id: 8,
      title: "لحم بقري",
      description: beef_des,
      amountScale: gramAmount,
      image: beef_image,
      calories: 217,
      protein: 26.1,
      fat: 11.8,
      carb: 0),
  FoodData(
      id: 9,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 10,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 11,
      title: "سمك بلطي",
      description: boltiFish_des,
      amountScale: gramAmount,
      image: boltiFish_image,
      calories: 128,
      protein: 26,
      fat: 2.7,
      carb: 0),
  FoodData(
      id: 12,
      title: "سمك بوري",
      description: boriFish_des,
      amountScale: gramAmount,
      image: boriFish_image,
      calories: 206,
      protein: 22,
      fat: 12,
      carb: 0),
  FoodData(
      id: 13,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 14,
      title: "جمبري",
      description: shrimp_des,
      amountScale: gramAmount,
      image: shrimp_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 15,
      title: "استاكوزا",
      description: estakoza_des,
      amountScale: gramAmount,
      image: estakoza_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 16,
      title: "حبار",
      description: habbar_des,
      amountScale: gramAmount,
      image: habbar_image,
      calories: 92,
      protein: 16,
      fat: 1.4,
      carb: 3.1),
  FoodData(
      id: 17,
      title: "لحم البط",
      description: duck_des,
      amountScale: gramAmount,
      image: duck_image,
      calories: 337,
      protein: 19,
      fat: 28,
      carb: 0),
  FoodData(
      id: 18,
      title: "لحم الديك الرومي",
      description: turkey_des,
      amountScale: gramAmount,
      image: turkey_image,
      calories: 147,
      protein: 30,
      fat: 2.2,
      carb: 0),
  FoodData(
      id: 19,
      title: "فول سوداني",
      description: peanut_des,
      amountScale: gramAmount,
      image: peanut_image,
      calories: 567,
      protein: 25.8,
      fat: 49.2,
      carb: 16.1),
  FoodData(
      id: 20,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 21,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 22,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 23,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 24,
      title: "حمص",
      description: hummos_des,
      amountScale: gramAmount,
      image: hummos_image,
      calories: 364,
      protein: 19,
      fat: 6,
      carb: 61),
  FoodData(
      id: 25,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 26,
      title: "بازلاء",
      description: besella_des,
      amountScale: gramAmount,
      image: besella_image,
      calories: 341,
      protein: 24.5,
      fat: 1.1,
      carb: 60.3),
  FoodData(
      id: 27,
      title: "فول",
      description: fool_des,
      amountScale: gramAmount,
      image: fool_image,
      calories: 341,
      protein: 26.1,
      fat: 1.5,
      carb: 58.3),
  FoodData(
      id: 28,
      title: "فلافل",
      description: falafel_des,
      amountScale: gramAmount,
      image: falafel_image,
      calories: 333,
      protein: 13.3,
      fat: 17.8,
      carb: 31.8),
  FoodData(
      id: 29,
      title: "فول الصويا",
      description: soyaFool_des,
      amountScale: gramAmount,
      image: soyaFool_image,
      calories: 471,
      protein: 35.2,
      fat: 25.4,
      carb: 33.5),
  FoodData(
      id: 30,
      title: "ترمس",
      description: termes_des,
      amountScale: gramAmount,
      image: termes_image,
      calories: 371,
      protein: 36.1,
      fat: 9.7,
      carb: 40.4),
  FoodData(
      id: 31,
      title: "لوبيا بيضاء",
      description: whiteLubya_des,
      amountScale: gramAmount,
      image: whiteLubya_image,
      calories: 336,
      protein: 23.5,
      fat: 1.3,
      carb: 60),
];
final List<FoodData> fatFoodList = [
  FoodData(
      id: 1,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 2,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 3,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 5,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 6,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 7,
      title: "فول سوداني",
      description: peanut_des,
      amountScale: gramAmount,
      image: peanut_image,
      calories: 567,
      protein: 25.8,
      fat: 49.2,
      carb: 16.1),
  FoodData(
      id: 8,
      title: "لب سوري",
      description: sunflowerPulp_des,
      amountScale: gramAmount,
      image: sunflowerPulp_image,
      calories: 619,
      protein: 17.2,
      fat: 56.8,
      carb: 20.6),
  FoodData(
      id: 9,
      title: "لب ابيض",
      description: whitePulp_des,
      amountScale: gramAmount,
      image: whitePulp_image,
      calories: 600,
      protein: 23.3,
      fat: 46.7,
      carb: 13.3),
  FoodData(
      id: 10,
      title: "لب سوبر",
      description: brownPulp_des,
      amountScale: gramAmount,
      image: brownPulp_image,
      calories: 557,
      protein: 28.3,
      fat: 47.3,
      carb: 15.2),
  FoodData(
      id: 11,
      title: "زيت الزيتون",
      description: oliveOil_des,
      amountScale: sponAmount,
      image: oliveOil_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 12,
      title: "زبدة",
      description: butter_des,
      amountScale: sponAmount,
      image: butter_image,
      calories: 102,
      protein: 0,
      fat: 12,
      carb: 0),
  FoodData(
      id: 13,
      title: "سمن",
      description: samn_des,
      amountScale: sponAmount,
      image: samn_image,
      calories: 120,
      protein: 0,
      fat: 14,
      carb: 0),
  FoodData(
      id: 14,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 15,
      title: "سمك بوري",
      description: boriFish_des,
      amountScale: gramAmount,
      image: boriFish_image,
      calories: 206,
      protein: 22,
      fat: 12,
      carb: 0),
  FoodData(
      id: 16,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
  FoodData(
      id: 17,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 18,
      title: "جبنة كريم",
      description: creemCheese_des,
      amountScale: gramAmount,
      image: creemCheese_image,
      calories: 342,
      protein: 6,
      fat: 34,
      carb: 4.1),
  FoodData(
      id: 19,
      title: "جبنة موتزاريلا",
      description: mozarellaCheese_des,
      amountScale: gramAmount,
      image: mozarellaCheese_image,
      calories: 280,
      protein: 28,
      fat: 17,
      carb: 3.1),
  FoodData(
      id: 20,
      title: "جبنة براميلي",
      description: barameleCheese_des,
      amountScale: gramAmount,
      image: barameleCheese_image,
      calories: 250,
      protein: 14.3,
      fat: 21.4,
      carb: 0),
  FoodData(
      id: 21,
      title: "جبنة ريكفورد",
      description: rekfordCheese_des,
      amountScale: gramAmount,
      image: rekfordCheese_image,
      calories: 369,
      protein: 22,
      fat: 31,
      carb: 2),
  FoodData(
      id: 22,
      title: "جبنة رومي",
      description: romyCheese_des,
      amountScale: gramAmount,
      image: romyCheese_image,
      calories: 380,
      protein: 23,
      fat: 30,
      carb: 1),
];
final List<FoodData> sodiumFoodList = [
  FoodData(
      id: 1,
      title: "خبز بلدي مصري",
      description: egyptionBread_des,
      amountScale: mediumAmount,
      image: egyptionBread_image,
      calories: 300,
      protein: 9.5,
      fat: 4.3,
      carb: 56),
  FoodData(
      id: 2,
      title: "خبز أبيض",
      description: whiteBread_des,
      amountScale: mediumAmount,
      image: whiteBread_image,
      calories: 266,
      protein: 9.8,
      fat: 2.6,
      carb: 55),
  FoodData(
      id: 3,
      title: "خبز فرنسي",
      description: frenchBread_des,
      amountScale: mediumAmount,
      image: frenchBread_image,
      calories: 319,
      protein: 13,
      fat: 2.1,
      carb: 61.9),
  FoodData(
      id: 5,
      title: "لانشون",
      description: lanshon_des,
      amountScale: gramAmount,
      image: lanshon_image,
      calories: 189,
      protein: 17.8,
      fat: 11.1,
      carb: 4.4),
  FoodData(
      id: 6,
      title: "بسطرمة",
      description: basterma_des,
      amountScale: gramAmount,
      image: basterma_image,
      calories: 95,
      protein: 19.6,
      fat: 1.1,
      carb: 1.5),
  FoodData(
      id: 7,
      title: "سلامي",
      description: salame_des,
      amountScale: gramAmount,
      image: salame_image,
      calories: 336,
      protein: 22,
      fat: 26,
      carb: 2.4),
  FoodData(
      id: 8,
      title: "بسكويت نشادر",
      description: biscets_des,
      amountScale: mediumAmount,
      image: biscets_image,
      calories: 251,
      protein: 4.6,
      fat: 12.7,
      carb: 30.3),
  FoodData(
      id: 9,
      title: "بطاطس",
      description: potato_des,
      amountScale: gramAmount,
      image: potato_image,
      calories: 77,
      protein: 2,
      fat: 0.1,
      carb: 17),
  FoodData(
      id: 10,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 11,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
  FoodData(
      id: 12,
      title: "جبنة سويسرية",
      description: swissCheese_des,
      amountScale: gramAmount,
      image: swissCheese_image,
      calories: 380,
      protein: 27,
      fat: 27.8,
      carb: 5.4),
  FoodData(
      id: 13,
      title: "جبنة قديمة",
      description: oldCheese_des,
      amountScale: gramAmount,
      image: oldCheese_image,
      calories: 250,
      protein: 14.5,
      fat: 21.4,
      carb: 0),
  FoodData(
      id: 14,
      title: "جبنة قريش",
      description: kareeshCheese_des,
      amountScale: gramAmount,
      image: kareeshCheese_image,
      calories: 81,
      protein: 10.4,
      fat: 2.3,
      carb: 4.7),
  FoodData(
      id: 15,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 16,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 17,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
];
final List<FoodData> potassiumFoodList = [
  FoodData(
      id: 1,
      title: "موز",
      description: banana_des,
      amountScale: mediumAmount,
      image: banana_image,
      calories: 105,
      protein: 1.3,
      fat: 0.4,
      carb: 27),
  FoodData(
      id: 2,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 3,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 4,
      title: "جوز الهند",
      description: coconut_des,
      amountScale: gramAmount,
      image: coconut_image,
      calories: 354,
      protein: 3.3,
      fat: 33,
      carb: 15),
  FoodData(
      id: 5,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 6,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 7,
      title: "جبنة موتزاريلا",
      description: mozarellaCheese_des,
      amountScale: gramAmount,
      image: mozarellaCheese_image,
      calories: 280,
      protein: 28,
      fat: 17,
      carb: 3.1),
  FoodData(
      id: 8,
      title: "محار البحر",
      description: mahar_des,
      amountScale: gramAmount,
      image: mahar_image,
      calories: 86,
      protein: 12,
      fat: 2.5,
      carb: 4),
  FoodData(
      id: 9,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 10,
      title: "جزر",
      description: carrot_des,
      amountScale: gramAmount,
      image: carrot_image,
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carb: 10),
  FoodData(
      id: 11,
      title: "طماطم",
      description: tomato_des,
      amountScale: gramAmount,
      image: tomato_image,
      calories: 18,
      protein: 0.9,
      fat: 0.2,
      carb: 3.9),
  FoodData(
      id: 12,
      title: "بنجر",
      description: beetroot_des,
      amountScale: gramAmount,
      image: beetroot_image,
      calories: 43,
      protein: 1.6,
      fat: 0.2,
      carb: 9.5),
  FoodData(
      id: 13,
      title: "حمص",
      description: hummos_des,
      amountScale: gramAmount,
      image: hummos_image,
      calories: 364,
      protein: 19,
      fat: 6,
      carb: 61),
  FoodData(
      id: 14,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 15,
      title: "بطاطس",
      description: potato_des,
      amountScale: gramAmount,
      image: potato_image,
      calories: 77,
      protein: 2,
      fat: 0.1,
      carb: 17),
  FoodData(
      id: 16,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 17,
      title: "فلفل حار",
      description: chilli_des,
      amountScale: gramAmount,
      image: chilli_image,
      calories: 40,
      protein: 1.9,
      fat: 0.4,
      carb: 9),
  FoodData(
      id: 18,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 19,
      title: "سلق",
      description: salq_des,
      amountScale: gramAmount,
      image: salq_image,
      calories: 19,
      protein: 1.8,
      fat: 3.7,
      carb: 0.2),
];
final List<FoodData> ironFoodList = [
  FoodData(
      id: 1,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 2,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 3,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 4,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 5,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 6,
      title: "حمص",
      description: hummos_des,
      amountScale: gramAmount,
      image: hummos_image,
      calories: 364,
      protein: 19,
      fat: 6,
      carb: 61),
  FoodData(
      id: 7,
      title: "شوكولاتة",
      description: chocolate_des,
      amountScale: gramAmount,
      image: chocolate_image,
      calories: 546,
      protein: 4.9,
      fat: 31,
      carb: 61),
  FoodData(
      id: 8,
      title: "طماطم",
      description: tomato_des,
      amountScale: gramAmount,
      image: tomato_image,
      calories: 18,
      protein: 0.9,
      fat: 0.2,
      carb: 3.9),
  FoodData(
      id: 9,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
];
final List<FoodData> zincFoodList = [
  FoodData(
      id: 1,
      title: "لحم بقري",
      description: beef_des,
      amountScale: gramAmount,
      image: beef_image,
      calories: 217,
      protein: 26.1,
      fat: 11.8,
      carb: 0),
  FoodData(
      id: 2,
      title: "لحم الضأن",
      description: lamb_des,
      amountScale: gramAmount,
      image: lamb_image,
      calories: 258,
      protein: 25.6,
      fat: 16.5,
      carb: 0),
  FoodData(
      id: 3,
      title: "لحم الماعز",
      description: goat_des,
      amountScale: gramAmount,
      image: goat_image,
      calories: 143,
      protein: 27,
      fat: 3,
      carb: 0),
  FoodData(
      id: 4,
      title: "لحم الغنم",
      description: sheep_des,
      amountScale: gramAmount,
      image: sheep_image,
      calories: 283,
      protein: 24.8,
      fat: 19.6,
      carb: 0),
  FoodData(
      id: 5,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 6,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
  FoodData(
      id: 7,
      title: "جبنة باراميزان",
      description: baramezanCheese_des,
      amountScale: gramAmount,
      image: baramezanCheese_image,
      calories: 431,
      protein: 38.4,
      fat: 28.6,
      carb: 4),
  FoodData(
      id: 8,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 9,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 10,
      title: "شوكولاتة",
      description: chocolate_des,
      amountScale: gramAmount,
      image: chocolate_image,
      calories: 546,
      protein: 4.9,
      fat: 31,
      carb: 61),
  FoodData(
      id: 11,
      title: "شوفان",
      description: oats_des,
      amountScale: gramAmount,
      image: oats_image,
      calories: 389,
      protein: 17,
      fat: 7,
      carb: 66.3),
  FoodData(
      id: 12,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 13,
      title: "بازلاء",
      description: besella_des,
      amountScale: gramAmount,
      image: besella_image,
      calories: 341,
      protein: 24.5,
      fat: 1.1,
      carb: 60.3),
  FoodData(
      id: 14,
      title: "فول",
      description: fool_des,
      amountScale: gramAmount,
      image: fool_image,
      calories: 341,
      protein: 26.1,
      fat: 1.5,
      carb: 58.3),
];
final List<FoodData> phosphorousFoodList = [
  FoodData(
      id: 1,
      title: "سمك بلطي",
      description: boltiFish_des,
      amountScale: gramAmount,
      image: boltiFish_image,
      calories: 128,
      protein: 26,
      fat: 2.7,
      carb: 0),
  FoodData(
      id: 2,
      title: "سمك بوري",
      description: boriFish_des,
      amountScale: gramAmount,
      image: boriFish_image,
      calories: 206,
      protein: 22,
      fat: 12,
      carb: 0),
  FoodData(
      id: 3,
      title: "سمك بربوني",
      description: barboniFish_des,
      amountScale: gramAmount,
      image: barboniFish_image,
      calories: 110,
      protein: 18.7,
      fat: 3.8,
      carb: 0),
  FoodData(
      id: 4,
      title: "سمك مرجان",
      description: morganFish_des,
      amountScale: gramAmount,
      image: morganFish_image,
      calories: 123,
      protein: 24.5,
      fat: 2.8,
      carb: 0),
  FoodData(
      id: 5,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 7,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 24,
      title: "جمبري",
      description: shrimp_des,
      amountScale: gramAmount,
      image: shrimp_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 25,
      title: "كابوريا",
      description: kaborya_des,
      amountScale: gramAmount,
      image: kaborya_image,
      calories: 83,
      protein: 18,
      fat: 0.7,
      carb: 0),
  FoodData(
      id: 26,
      title: "استاكوزا",
      description: estakoza_des,
      amountScale: gramAmount,
      image: estakoza_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
  FoodData(
      id: 27,
      title: "حبار",
      description: habbar_des,
      amountScale: gramAmount,
      image: habbar_image,
      calories: 92,
      protein: 16,
      fat: 1.4,
      carb: 3.1),
  FoodData(
      id: 28,
      title: "محار البحر",
      description: mahar_des,
      amountScale: gramAmount,
      image: mahar_image,
      calories: 86,
      protein: 12,
      fat: 2.5,
      carb: 4),
  FoodData(
      id: 4,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 1,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 10,
      title: "لحم الديك الرومي",
      description: turkey_des,
      amountScale: gramAmount,
      image: turkey_image,
      calories: 147,
      protein: 30,
      fat: 2.2,
      carb: 0),
  FoodData(
      id: 1,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 2,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 3,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 4,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 5,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 19,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 5,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 13,
      title: "جبنة رومي",
      description: romyCheese_des,
      amountScale: gramAmount,
      image: romyCheese_image,
      calories: 380,
      protein: 23,
      fat: 30,
      carb: 1),
];
final List<FoodData> calciumFoodList = [
  FoodData(
      id: 1,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 2,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
  FoodData(
      id: 3,
      title: "جبنة باراميزان",
      description: baramezanCheese_des,
      amountScale: gramAmount,
      image: baramezanCheese_image,
      calories: 431,
      protein: 38.4,
      fat: 28.6,
      carb: 4),
  FoodData(
      id: 4,
      title: "جبنة حلوم",
      description: halomCheese_des,
      amountScale: gramAmount,
      image: halomCheese_image,
      calories: 393,
      protein: 25,
      fat: 32.1,
      carb: 3.6),
  FoodData(
      id: 5,
      title: "جبنة ريكوتا",
      description: rekotaCheese_des,
      amountScale: gramAmount,
      image: rekotaCheese_image,
      calories: 428,
      protein: 28,
      fat: 32,
      carb: 7),
  FoodData(
      id: 6,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 7,
      title: "جبنة توفو",
      description: tofoCheese_des,
      amountScale: gramAmount,
      image: tofoCheese_image,
      calories: 270,
      protein: 18.8,
      fat: 20.2,
      carb: 8.8),
  FoodData(
      id: 8,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 9,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
  FoodData(
      id: 10,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 11,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 12,
      title: "عدس",
      description: lentil_des,
      amountScale: gramAmount,
      image: lentil_image,
      calories: 353,
      protein: 25.8,
      fat: 1,
      carb: 60),
  FoodData(
      id: 13,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 14,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
];
final List<FoodData> vitaminAFoodList = [
  FoodData(
      id: 1,
      title: "بطاطا حلوه",
      description: potatoSweet_des,
      amountScale: gramAmount,
      image: potatoSweet_image,
      calories: 86,
      protein: 1.6,
      fat: 0,
      carb: 20),
  FoodData(
      id: 2,
      title: "فلفل حلو",
      description: pepper_des,
      amountScale: gramAmount,
      image: pepper_image,
      calories: 40,
      protein: 2,
      fat: 0.2,
      carb: 9),
  FoodData(
      id: 3,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 4,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 5,
      title: "بصل",
      description: onion_des,
      amountScale: gramAmount,
      image: onion_image,
      calories: 40,
      protein: 1.1,
      fat: 0.1,
      carb: 9),
  FoodData(
      id: 6,
      title: "جزر",
      description: carrot_des,
      amountScale: gramAmount,
      image: carrot_image,
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carb: 10),
  FoodData(
      id: 7,
      title: "شمام",
      description: melon_des,
      amountScale: gramAmount,
      image: melon_image,
      calories: 34,
      protein: 0.8,
      fat: 0.2,
      carb: 8),
  FoodData(
      id: 8,
      title: "مانجا",
      description: mango_des,
      amountScale: mediumAmount,
      image: mango_image,
      calories: 201,
      protein: 2.8,
      fat: 1.3,
      carb: 50),
  FoodData(
      id: 9,
      title: "مشمش",
      description: apricot_des,
      amountScale: mediumAmount,
      image: apricot_image,
      calories: 17,
      protein: 0.5,
      fat: 0.1,
      carb: 3.9),
  FoodData(
      id: 10,
      title: "قرع العسل",
      description: pumpkin_des,
      amountScale: gramAmount,
      image: pumpkin_image,
      calories: 26,
      protein: 1,
      fat: 0.1,
      carb: 6.5),
  FoodData(
      id: 11,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 12,
      title: "لوبيا الخضراء",
      description: lubya_des,
      amountScale: gramAmount,
      image: lubya_image,
      calories: 336,
      protein: 24,
      fat: 1.3,
      carb: 60),
  FoodData(
      id: 13,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 14,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 15,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 16,
      title: "فول سوداني",
      description: peanut_des,
      amountScale: gramAmount,
      image: peanut_image,
      calories: 567,
      protein: 25.8,
      fat: 49.2,
      carb: 16.1),
  FoodData(
      id: 17,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 18,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 19,
      title: "لبن رائب",
      description: yoghurt_des,
      amountScale: cupAmount,
      image: yoghurt_image,
      calories: 151,
      protein: 8,
      fat: 8,
      carb: 12),
  FoodData(
      id: 20,
      title: "سمك رنجة",
      description: rengaFish_des,
      amountScale: gramAmount,
      image: rengaFish_image,
      calories: 217,
      protein: 25,
      fat: 12,
      carb: 0),
  FoodData(
      id: 21,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 22,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 23,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 24,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 25,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
];
final List<FoodData> vitaminBFoodList = [
  FoodData(
      id: 1,
      title: "بيض",
      description: egg_des,
      amountScale: mediumAmount,
      image: egg_image,
      calories: 72,
      protein: 6.3,
      fat: 4.6,
      carb: 0.8),
  FoodData(
      id: 2,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 3,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
  FoodData(
      id: 4,
      title: "لحم الديك الرومي",
      description: turkey_des,
      amountScale: gramAmount,
      image: turkey_image,
      calories: 147,
      protein: 30,
      fat: 2.2,
      carb: 0),
  FoodData(
      id: 5,
      title: "كبد بقري",
      description: kebda_des,
      amountScale: gramAmount,
      image: kebda_image,
      calories: 165,
      protein: 26,
      fat: 4.4,
      carb: 3.8),
  FoodData(
      id: 6,
      title: "لب سوري",
      description: sunflowerPulp_des,
      amountScale: gramAmount,
      image: sunflowerPulp_image,
      calories: 619,
      protein: 17.2,
      fat: 56.8,
      carb: 20.6),
  FoodData(
      id: 7,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 8,
      title: "محار البحر",
      description: mahar_des,
      amountScale: gramAmount,
      image: mahar_image,
      calories: 86,
      protein: 12,
      fat: 2.5,
      carb: 4),
  FoodData(
      id: 9,
      title: "فاصوليا بيضاء",
      description: whiteFasolia_des,
      amountScale: gramAmount,
      image: whiteFasolia_image,
      calories: 336,
      protein: 21.1,
      fat: 1.1,
      carb: 62.3),
  FoodData(
      id: 10,
      title: "بازلاء",
      description: besella_des,
      amountScale: gramAmount,
      image: besella_image,
      calories: 341,
      protein: 24.5,
      fat: 1.1,
      carb: 60.3),
  FoodData(
      id: 11,
      title: "فول",
      description: fool_des,
      amountScale: gramAmount,
      image: fool_image,
      calories: 341,
      protein: 26.1,
      fat: 1.5,
      carb: 58.3),
  FoodData(
      id: 12,
      title: "فول الصويا",
      description: soyaFool_des,
      amountScale: gramAmount,
      image: soyaFool_image,
      calories: 471,
      protein: 35.2,
      fat: 25.4,
      carb: 33.5),
  FoodData(
      id: 13,
      title: "لوبيا بيضاء",
      description: whiteLubya_des,
      amountScale: gramAmount,
      image: whiteLubya_image,
      calories: 336,
      protein: 23.5,
      fat: 1.3,
      carb: 60),
  FoodData(
      id: 14,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 15,
      title: "جرجير",
      description: watercress_des,
      amountScale: gramAmount,
      image: watercress_image,
      calories: 25,
      protein: 2.6,
      fat: 3.6,
      carb: 0.6),
  FoodData(
      id: 16,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
];
final List<FoodData> vitaminCFoodList = [
  FoodData(
      id: 1,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 2,
      title: "ليمون",
      description: lemon_des,
      amountScale: mediumAmount,
      image: lemon_image,
      calories: 17,
      protein: 0.6,
      fat: 0.2,
      carb: 5),
  FoodData(
      id: 3,
      title: "يوسفي",
      description: mandarin_des,
      amountScale: mediumAmount,
      image: mandarin_image,
      calories: 47,
      protein: 0.7,
      fat: 0.3,
      carb: 11.7),
  FoodData(
      id: 4,
      title: "كيوي",
      description: kiwi_des,
      amountScale: mediumAmount,
      image: kiwi_image,
      calories: 42,
      protein: 0.8,
      fat: 0.4,
      carb: 10),
  FoodData(
      id: 5,
      title: "جوافة",
      description: guava_des,
      amountScale: mediumAmount,
      image: guava_image,
      calories: 38,
      protein: 1.4,
      fat: 0.5,
      carb: 8),
  FoodData(
      id: 6,
      title: "فراولة",
      description: strawberry_des,
      amountScale: gramAmount,
      image: strawberry_image,
      calories: 33,
      protein: 0.7,
      fat: 0.3,
      carb: 8),
  FoodData(
      id: 7,
      title: "بابايا",
      description: papaya_des,
      amountScale: gramAmount,
      image: papaya_image,
      calories: 39,
      protein: 0.6,
      fat: 0.1,
      carb: 9.8),
  FoodData(
      id: 8,
      title: "قرنبيط",
      description: qarnabeet_des,
      amountScale: gramAmount,
      image: qarnabeet_image,
      calories: 25,
      protein: 1.9,
      fat: 0.3,
      carb: 5),
  FoodData(
      id: 9,
      title: "فلفل الحلو",
      description: pepper_des,
      amountScale: gramAmount,
      image: pepper_image,
      calories: 40,
      protein: 2,
      fat: 0.2,
      carb: 9),
  FoodData(
      id: 10,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
];
final List<FoodData> vitaminKFoodList = [
  FoodData(
      id: 1,
      title: "قرع العسل",
      description: pumpkin_des,
      amountScale: gramAmount,
      image: pumpkin_image,
      calories: 26,
      protein: 1,
      fat: 0.1,
      carb: 6.5),
  FoodData(
      id: 2,
      title: "رمان",
      description: pomegranate_des,
      amountScale: gramAmount,
      image: pomegranate_image,
      calories: 83,
      protein: 1.7,
      fat: 1.1,
      carb: 18.7),
  FoodData(
      id: 3,
      title: "توت أزرق",
      description: blueberry_des,
      amountScale: gramAmount,
      image: blueberry_image,
      calories: 57,
      protein: 0.7,
      fat: 0.3,
      carb: 14),
  FoodData(
      id: 4,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 5,
      title: "باميا",
      description: okra_des,
      amountScale: gramAmount,
      image: okra_image,
      calories: 33,
      protein: 1.9,
      fat: 0.2,
      carb: 7),
  FoodData(
      id: 6,
      title: "خس",
      description: lettuce_des,
      amountScale: gramAmount,
      image: lettuce_image,
      calories: 17,
      protein: 1.2,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 7,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 8,
      title: "كرنب",
      description: cabbage_des,
      amountScale: gramAmount,
      image: cabbage_image,
      calories: 25,
      protein: 1.3,
      fat: 0.1,
      carb: 5.8),
  FoodData(
      id: 9,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 10,
      title: "جزر",
      description: carrot_des,
      amountScale: gramAmount,
      image: carrot_image,
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carb: 10),
  FoodData(
      id: 11,
      title: "فول الصويا",
      description: soyaFool_des,
      amountScale: gramAmount,
      image: soyaFool_image,
      calories: 471,
      protein: 35.2,
      fat: 25.4,
      carb: 33.5),
  FoodData(
      id: 12,
      title: "صدور الدجاج",
      description: chickenChest_des,
      amountScale: gramAmount,
      image: chickenChest_image,
      calories: 165,
      protein: 31,
      fat: 3.6,
      carb: 0),
];
final List<FoodData> vitaminDFoodList = [
  FoodData(
      id: 1,
      title: "سمك سردين",
      description: sardenFish_des,
      amountScale: gramAmount,
      image: sardenFish_image,
      calories: 143,
      protein: 18,
      fat: 7,
      carb: 0),
  FoodData(
      id: 2,
      title: "سمك تونة",
      description: tunaFish_des,
      amountScale: gramAmount,
      image: tunaFish_image,
      calories: 132,
      protein: 28,
      fat: 1.3,
      carb: 0),
  FoodData(
      id: 3,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 4,
      title: "صفار البيض",
      description: eggYork_des,
      amountScale: mediumAmount,
      image: eggYork_image,
      calories: 55,
      protein: 2.7,
      fat: 4.5,
      carb: 0.6),
  FoodData(
      id: 5,
      title: "حليب البقر",
      description: cowMilk_des,
      amountScale: cupAmount,
      image: cowMilk_image,
      calories: 103,
      protein: 8,
      fat: 2.4,
      carb: 12),
  FoodData(
      id: 6,
      title: "جبنة شيدر",
      description: cheddarCheese_des,
      amountScale: gramAmount,
      image: cheddarCheese_image,
      calories: 403,
      protein: 24.9,
      fat: 33.1,
      carb: 1.3),
  FoodData(
      id: 7,
      title: "جبنة فيتا",
      description: fetaCheese_des,
      amountScale: gramAmount,
      image: fetaCheese_image,
      calories: 264,
      protein: 14.2,
      fat: 21.3,
      carb: 4),
  FoodData(
      id: 8,
      title: "شوفان",
      description: oats_des,
      amountScale: gramAmount,
      image: oats_image,
      calories: 389,
      protein: 17,
      fat: 7,
      carb: 66.3),
  FoodData(
      id: 9,
      title: "برتقال",
      description: orange_des,
      amountScale: mediumAmount,
      image: orange_image,
      calories: 62,
      protein: 1.2,
      fat: 0.2,
      carb: 15),
  FoodData(
      id: 10,
      title: "مشروم",
      description: mashroom_des,
      amountScale: gramAmount,
      image: mashroom_image,
      calories: 22,
      protein: 3.1,
      fat: 0.3,
      carb: 3.3),
  FoodData(
      id: 11,
      title: "زبدة",
      description: butter_des,
      amountScale: sponAmount,
      image: butter_image,
      calories: 102,
      protein: 0,
      fat: 12,
      carb: 0),
  FoodData(
      id: 12,
      title: "شوكولاتة",
      description: chocolate_des,
      amountScale: gramAmount,
      image: chocolate_image,
      calories: 546,
      protein: 4.9,
      fat: 31,
      carb: 61)
];
final List<FoodData> vitaminEFoodList = [
  FoodData(
      id: 1,
      title: "لوز",
      description: almond_des,
      amountScale: gramAmount,
      image: almond_image,
      calories: 579,
      protein: 21,
      carb: 21.5,
      fat: 50),
  FoodData(
      id: 2,
      title: "بندق",
      description: hazelnut_des,
      amountScale: gramAmount,
      image: hazelnut_image,
      calories: 628,
      protein: 15,
      fat: 60.7,
      carb: 16.7),
  FoodData(
      id: 3,
      title: "عين الجمل",
      description: walnut_des,
      amountScale: gramAmount,
      image: walnut_image,
      calories: 654,
      protein: 15.2,
      fat: 65.2,
      carb: 13.7),
  FoodData(
      id: 4,
      title: "كاجو",
      description: cashew_des,
      amountScale: gramAmount,
      image: cashew_image,
      calories: 553,
      protein: 18.2,
      fat: 43.8,
      carb: 30.2),
  FoodData(
      id: 5,
      title: "فستق",
      description: pistachio_des,
      amountScale: gramAmount,
      image: pistachio_image,
      calories: 562,
      protein: 20.3,
      fat: 45.4,
      carb: 27.5),
  FoodData(
      id: 6,
      title: "فول سوداني",
      description: peanut_des,
      amountScale: gramAmount,
      image: peanut_image,
      calories: 567,
      protein: 25.8,
      fat: 49.2,
      carb: 16.1),
  FoodData(
      id: 7,
      title: "لب سوري",
      description: sunflowerPulp_des,
      amountScale: gramAmount,
      image: sunflowerPulp_image,
      calories: 619,
      protein: 17.2,
      fat: 56.8,
      carb: 20.6),
  FoodData(
      id: 8,
      title: "سبانخ",
      description: spinach_des,
      amountScale: gramAmount,
      image: spinach_image,
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carb: 3.6),
  FoodData(
      id: 9,
      title: "سلق",
      description: salq_des,
      amountScale: gramAmount,
      image: salq_image,
      calories: 19,
      protein: 1.8,
      fat: 3.7,
      carb: 0.2),
  FoodData(
      id: 10,
      title: "بروكلي",
      description: broccoli_des,
      amountScale: gramAmount,
      image: broccoli_image,
      calories: 34,
      protein: 2.8,
      fat: 0.4,
      carb: 6.6),
  FoodData(
      id: 11,
      title: "افوكادو",
      description: avocado_des,
      amountScale: mediumAmount,
      image: avocado_image,
      calories: 322,
      protein: 4,
      fat: 29,
      carb: 17),
  FoodData(
      id: 12,
      title: "زيتون",
      description: olive_des,
      amountScale: gramAmount,
      image: olive_image,
      calories: 115,
      protein: 0.8,
      fat: 11,
      carb: 6),
  FoodData(
      id: 13,
      title: "سمك سلمون",
      description: salamonFish_des,
      amountScale: gramAmount,
      image: salamonFish_image,
      calories: 206,
      protein: 22.1,
      fat: 12.2,
      carb: 0),
  FoodData(
      id: 14,
      title: "جمبري",
      description: shrimp_des,
      amountScale: gramAmount,
      image: shrimp_image,
      calories: 120,
      protein: 22,
      fat: 1.8,
      carb: 1.6),
];
