import 'package:food_app/RecipesDatabase.dart';

class RecipeAssets {
  int id;
  String name, image, ingredients, prepare;
  int cookingTime, mealsNo, calories;
  int protein, fat, carb;
  String sts = RecipesPrepare.noodles;

  RecipeAssets(
      {required this.id,
      required this.name,
      required this.image,
      required this.cookingTime,
      required this.mealsNo,
      required this.ingredients,
      required this.prepare,
      required this.calories,
      required this.protein,
      required this.fat,
      required this.carb});
}

final List<RecipeAssets> mainDishesList = [
  RecipeAssets(
      id: 1,
      name: "الفاهيتا المكسيكية",
      cookingTime: 75,
      mealsNo: 6,
      image: RecipesImage.mainDishe1,
      ingredients: RecipesIngredients.mainDishe1,
      prepare: RecipesPrepare.mainDishe1,
      calories: 615,
      protein: 63,
      fat: 14,
      carb: 63),
  RecipeAssets(
      id: 13,
      name: "النودلز الصيني باللحم",
      mealsNo: 2,
      cookingTime: 45,
      image: RecipesImage.mainDishe13,
      ingredients: RecipesIngredients.mainDishe13,
      prepare: RecipesPrepare.mainDishe13,
      calories: 1045,
      protein: 59,
      fat: 28,
      carb: 141),
  RecipeAssets(
      id: 3,
      name: "جمبري سويت آند ساور",
      mealsNo: 4,
      cookingTime: 30,
      image: RecipesImage.mainDishe7,
      ingredients: RecipesIngredients.mainDishe7,
      prepare: RecipesPrepare.mainDishe7,
      calories: 283,
      protein: 29,
      fat: 6,
      carb: 27),
  RecipeAssets(
      id: 4,
      name: "السليق الحجازي بالدجاج",
      mealsNo: 8,
      cookingTime: 80,
      image: RecipesImage.mainDishe4,
      ingredients: RecipesIngredients.mainDishe4,
      prepare: RecipesPrepare.mainDishe4,
      calories: 800,
      protein: 70,
      fat: 17,
      carb: 86),
  RecipeAssets(
      id: 7,
      name: "كريب فاهيتا",
      mealsNo: 6,
      cookingTime: 90,
      image: RecipesImage.mainDishe3,
      ingredients: RecipesIngredients.mainDishe3,
      prepare: RecipesPrepare.mainDishe3,
      calories: 463,
      protein: 35,
      fat: 17,
      carb: 41),
  RecipeAssets(
      id: 5,
      name: "ورق عنب كيتو",
      mealsNo: 8,
      cookingTime: 85,
      image: RecipesImage.mainDishe5,
      ingredients: RecipesIngredients.mainDishe5,
      prepare: RecipesPrepare.mainDishe5,
      calories: 337,
      protein: 15,
      fat: 12,
      carb: 44),
  RecipeAssets(
      id: 6,
      name: "باستا القصدير بالدجاج",
      mealsNo: 4,
      cookingTime: 35,
      image: RecipesImage.mainDishe6,
      ingredients: RecipesIngredients.mainDishe6,
      prepare: RecipesPrepare.mainDishe6,
      calories: 763,
      protein: 56,
      fat: 23,
      carb: 81),
  RecipeAssets(
      id: 8,
      name: "فتة الشيش طاووق",
      mealsNo: 6,
      cookingTime: 50,
      image: RecipesImage.mainDishe8,
      ingredients: RecipesIngredients.mainDishe8,
      prepare: RecipesPrepare.mainDishe8,
      calories: 1012,
      protein: 61,
      fat: 34,
      carb: 113),
  RecipeAssets(
      id: 9,
      name: "لازانيا بدون لحم",
      mealsNo: 8,
      cookingTime: 70,
      image: RecipesImage.mainDishe9,
      ingredients: RecipesIngredients.mainDishe9,
      prepare: RecipesPrepare.mainDishe9,
      calories: 708,
      protein: 47,
      fat: 35,
      carb: 51),
  RecipeAssets(
      id: 10,
      name: "زربيان اللحم العدني",
      mealsNo: 6,
      cookingTime: 105,
      image: RecipesImage.mainDishe10,
      ingredients: RecipesIngredients.mainDishe10,
      prepare: RecipesPrepare.mainDishe10,
      calories: 733,
      protein: 52,
      fat: 26,
      carb: 70),
  RecipeAssets(
      id: 11,
      name: "مقلقل لحم وكبدة",
      mealsNo: 6,
      cookingTime: 90,
      image: RecipesImage.mainDishe11,
      ingredients: RecipesIngredients.mainDishe11,
      prepare: RecipesPrepare.mainDishe11,
      calories: 466,
      protein: 45,
      fat: 24,
      carb: 15),
  RecipeAssets(
      id: 12,
      name: "الرقش باللحم",
      mealsNo: 6,
      cookingTime: 75,
      image: RecipesImage.mainDishe12,
      ingredients: RecipesIngredients.mainDishe12,
      prepare: RecipesPrepare.mainDishe12,
      calories: 500,
      protein: 43,
      fat: 32,
      carb: 7),
  RecipeAssets(
      id: 14,
      name: "الرامن الكوري بالبيض",
      mealsNo: 2,
      cookingTime: 15,
      image: RecipesImage.mainDishe14,
      ingredients: RecipesIngredients.mainDishe14,
      prepare: RecipesPrepare.mainDishe14,
      calories: 840,
      protein: 30,
      fat: 21,
      carb: 130),
  RecipeAssets(
      id: 15,
      name: "فطيرة البورتوبيلو",
      mealsNo: 4,
      cookingTime: 60,
      image: RecipesImage.mainDishe15,
      ingredients: RecipesIngredients.mainDishe15,
      prepare: RecipesPrepare.mainDishe15,
      calories: 431,
      protein: 27,
      fat: 21,
      carb: 38),
  RecipeAssets(
      id: 16,
      name: "البامية العراقية",
      mealsNo: 5,
      cookingTime: 75,
      image: RecipesImage.mainDishe16,
      ingredients: RecipesIngredients.mainDishe16,
      prepare: RecipesPrepare.mainDishe16,
      calories: 367,
      protein: 29,
      fat: 20,
      carb: 19),
  RecipeAssets(
      id: 17,
      name: "سمك الهامور المقلي",
      mealsNo: 6,
      cookingTime: 50,
      image: RecipesImage.mainDishe17,
      ingredients: RecipesIngredients.mainDishe17,
      prepare: RecipesPrepare.mainDishe17,
      calories: 635,
      protein: 80,
      fat: 5,
      carb: 52),
  RecipeAssets(
      id: 18,
      name: "السجق الشامي على الحطب",
      mealsNo: 6,
      cookingTime: 60,
      image: RecipesImage.mainDishe18,
      ingredients: RecipesIngredients.mainDishe18,
      prepare: RecipesPrepare.mainDishe18,
      calories: 605,
      protein: 49,
      fat: 27,
      carb: 38),
  RecipeAssets(
      id: 19,
      name: "العصبان الليبي",
      mealsNo: 10,
      cookingTime: 120,
      image: RecipesImage.mainDishe19,
      ingredients: RecipesIngredients.mainDishe19,
      prepare: RecipesPrepare.mainDishe19,
      calories: 440,
      protein: 21,
      fat: 15,
      carb: 66),
  RecipeAssets(
      id: 20,
      name: "طبق علي نازك التركي",
      mealsNo: 4,
      cookingTime: 90,
      image: RecipesImage.mainDishe20,
      ingredients: RecipesIngredients.mainDishe20,
      prepare: RecipesPrepare.mainDishe20,
      calories: 550,
      protein: 40,
      fat: 35,
      carb: 19),
  RecipeAssets(
      id: 21,
      name: "الطرشانة النجفية باللحم",
      mealsNo: 4,
      cookingTime: 40,
      image: RecipesImage.mainDishe21,
      ingredients: RecipesIngredients.mainDishe21,
      prepare: RecipesPrepare.mainDishe21,
      calories: 520,
      protein: 37,
      fat: 31,
      carb: 26),
  RecipeAssets(
      id: 22,
      name: "كفتة الفريك",
      mealsNo: 4,
      cookingTime: 45,
      image: RecipesImage.mainDishe22,
      ingredients: RecipesIngredients.mainDishe22,
      prepare: RecipesPrepare.mainDishe22,
      calories: 408,
      protein: 37,
      fat: 16,
      carb: 26),
  RecipeAssets(
      id: 23,
      name: "مكرونة بشاميل بالجبنة",
      mealsNo: 6,
      cookingTime: 80,
      image: RecipesImage.mainDishe23,
      ingredients: RecipesIngredients.mainDishe23,
      prepare: RecipesPrepare.mainDishe23,
      calories: 549,
      protein: 35,
      fat: 26,
      carb: 128),
  RecipeAssets(
      id: 24,
      name: "مكرونة بشاميل بفاهيتا اللحم",
      mealsNo: 6,
      cookingTime: 90,
      image: RecipesImage.mainDishe24,
      ingredients: RecipesIngredients.mainDishe24,
      prepare: RecipesPrepare.mainDishe24,
      calories: 860,
      protein: 46,
      fat: 41,
      carb: 64),
  RecipeAssets(
      id: 25,
      name: "المحشوش الجيزاني",
      mealsNo: 5,
      cookingTime: 70,
      image: RecipesImage.mainDishe25,
      ingredients: RecipesIngredients.mainDishe25,
      prepare: RecipesPrepare.mainDishe25,
      calories: 619,
      protein: 47,
      fat: 22,
      carb: 0),
  RecipeAssets(
      id: 26,
      name: "الدغابيس باللحم",
      mealsNo: 5,
      cookingTime: 80,
      image: RecipesImage.mainDishe26,
      ingredients: RecipesIngredients.mainDishe26,
      prepare: RecipesPrepare.mainDishe26,
      calories: 718,
      protein: 60,
      fat: 24,
      carb: 59),
  RecipeAssets(
      id: 27,
      name: "جرجانية",
      mealsNo: 4,
      cookingTime: 40,
      image: RecipesImage.mainDishe27,
      ingredients: RecipesIngredients.mainDishe27,
      prepare: RecipesPrepare.mainDishe27,
      calories: 401,
      protein: 34,
      fat: 21,
      carb: 17),
  RecipeAssets(
      id: 28,
      name: "دجاج منشوريان الصيني",
      mealsNo: 6,
      cookingTime: 50,
      image: RecipesImage.mainDishe28,
      ingredients: RecipesIngredients.mainDishe28,
      prepare: RecipesPrepare.mainDishe28,
      calories: 274,
      protein: 28,
      fat: 9,
      carb: 19),
  RecipeAssets(
      id: 29,
      name: "فاهيتا لحم الضأن",
      mealsNo: 4,
      cookingTime: 45,
      image: RecipesImage.mainDishe29,
      ingredients: RecipesIngredients.mainDishe29,
      prepare: RecipesPrepare.mainDishe29,
      calories: 544,
      protein: 42,
      fat: 32,
      carb: 23),
  RecipeAssets(
      id: 30,
      name: "محشي السلق ببهارات الكاري والكركم وعصير الليمون",
      mealsNo: 8,
      cookingTime: 100,
      image: RecipesImage.mainDishe30,
      ingredients: RecipesIngredients.mainDishe30,
      prepare: RecipesPrepare.mainDishe30,
      calories: 455,
      protein: 19,
      fat: 23,
      carb: 51),
];

final List<RecipeAssets> sideDishesList = [
  RecipeAssets(
      id: 1,
      name: "الإندومي بالجبن",
      image: RecipesImage.sideDishe1,
      cookingTime: 15,
      mealsNo: 1,
      ingredients: RecipesIngredients.sideDishe1,
      prepare: RecipesPrepare.sideDishe1,
      calories: 843,
      protein: 44,
      fat: 27,
      carb: 103),
  RecipeAssets(
      id: 2,
      name: "رأس العصفور",
      image: RecipesImage.sideDishe2,
      cookingTime: 60,
      mealsNo: 3,
      ingredients: RecipesIngredients.sideDishe2,
      prepare: RecipesPrepare.sideDishe2,
      calories: 410,
      protein: 35,
      fat: 14,
      carb: 34),
  RecipeAssets(
      id: 3,
      name: "مسخن بعجينة السمبوسة",
      image: RecipesImage.sideDishe3,
      cookingTime: 60,
      mealsNo: 10,
      ingredients: RecipesIngredients.sideDishe3,
      prepare: RecipesPrepare.sideDishe3,
      calories: 180,
      protein: 18,
      fat: 7,
      carb: 13),
  RecipeAssets(
      id: 4,
      name: "جريش بالشوفان",
      image: RecipesImage.sideDishe4,
      cookingTime: 35,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe4,
      prepare: RecipesPrepare.sideDishe4,
      calories: 719,
      protein: 33,
      fat: 23,
      carb: 100),
  RecipeAssets(
      id: 5,
      name: "كروكيت أرز بالجبن",
      image: RecipesImage.sideDishe5,
      cookingTime: 55,
      mealsNo: 16,
      ingredients: RecipesIngredients.sideDishe5,
      prepare: RecipesPrepare.sideDishe5,
      calories: 174,
      protein: 7,
      fat: 5,
      carb: 24),
  RecipeAssets(
      id: 6,
      name: "لفائف الكفتة بالجلاش",
      image: RecipesImage.sideDishe6,
      cookingTime: 30,
      mealsNo: 5,
      ingredients: RecipesIngredients.sideDishe6,
      prepare: RecipesPrepare.sideDishe6,
      calories: 505,
      protein: 41,
      fat: 31,
      carb: 16),
  RecipeAssets(
      id: 7,
      name: "أرز بالبرتقال",
      image: RecipesImage.sideDishe7,
      cookingTime: 40,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe7,
      prepare: RecipesPrepare.sideDishe7,
      calories: 314,
      protein: 6,
      fat: 5,
      carb: 61),
  RecipeAssets(
      id: 8,
      name: "مكعبات الكراميل بالخبز",
      image: RecipesImage.sideDishe8,
      cookingTime: 10,
      mealsNo: 5,
      ingredients: RecipesIngredients.sideDishe8,
      prepare: RecipesPrepare.sideDishe8,
      calories: 140,
      protein: 3,
      fat: 5,
      carb: 22),
  RecipeAssets(
      id: 9,
      name: "فطائر الماء التركية",
      image: RecipesImage.sideDishe9,
      cookingTime: 100,
      mealsNo: 12,
      ingredients: RecipesIngredients.sideDishe9,
      prepare: RecipesPrepare.sideDishe9,
      calories: 616,
      protein: 20,
      fat: 20,
      carb: 85),
  RecipeAssets(
      id: 10,
      name: "اليغمش اليمني",
      image: RecipesImage.sideDishe10,
      cookingTime: 45,
      mealsNo: 4,
      ingredients: RecipesIngredients.sideDishe10,
      prepare: RecipesPrepare.sideDishe10,
      calories: 272,
      protein: 8,
      fat: 1,
      carb: 57),
  RecipeAssets(
      id: 11,
      name: "صينية البطاطس بالكريمة اللباني",
      image: RecipesImage.sideDishe11,
      cookingTime: 45,
      mealsNo: 5,
      ingredients: RecipesIngredients.sideDishe11,
      prepare: RecipesPrepare.sideDishe11,
      calories: 441,
      protein: 14,
      fat: 27,
      carb: 36),
  RecipeAssets(
      id: 12,
      name: "المبطن الليبي بالدجاج",
      image: RecipesImage.sideDishe12,
      cookingTime: 75,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe12,
      prepare: RecipesPrepare.sideDishe12,
      calories: 487,
      protein: 32,
      fat: 14,
      carb: 56),
  RecipeAssets(
      id: 13,
      name: "المنتو الكذاب برقاق السمبوسة",
      image: RecipesImage.sideDishe13,
      cookingTime: 60,
      mealsNo: 4,
      ingredients: RecipesIngredients.sideDishe13,
      prepare: RecipesPrepare.sideDishe13,
      calories: 438,
      protein: 25,
      fat: 20,
      carb: 44),
  RecipeAssets(
      id: 14,
      name: "المنتو الكذاب بالدجاج",
      image: RecipesImage.sideDishe14,
      cookingTime: 80,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe14,
      prepare: RecipesPrepare.sideDishe14,
      calories: 548,
      protein: 46,
      fat: 25,
      carb: 34),
  RecipeAssets(
      id: 15,
      name: "الكوشينا البرازيلية",
      image: RecipesImage.sideDishe15,
      cookingTime: 110,
      mealsNo: 12,
      ingredients: RecipesIngredients.sideDishe15,
      prepare: RecipesPrepare.sideDishe15,
      calories: 380,
      protein: 26,
      fat: 12,
      carb: 40),
  RecipeAssets(
      id: 16,
      name: "صفيحة لحم بدبس الرمان",
      image: RecipesImage.sideDishe16,
      cookingTime: 75,
      mealsNo: 12,
      ingredients: RecipesIngredients.sideDishe16,
      prepare: RecipesPrepare.sideDishe16,
      calories: 320,
      protein: 16,
      fat: 12,
      carb: 34),
  RecipeAssets(
      id: 17,
      name: "كسرة حبشية",
      image: RecipesImage.sideDishe17,
      cookingTime: 75,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe17,
      prepare: RecipesPrepare.sideDishe17,
      calories: 236,
      protein: 7,
      fat: 1,
      carb: 50),
  RecipeAssets(
      id: 18,
      name: "سبرنج رول دجاج صيني",
      image: RecipesImage.sideDishe18,
      cookingTime: 30,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe18,
      prepare: RecipesPrepare.sideDishe18,
      calories: 474,
      protein: 35,
      fat: 10,
      carb: 60),
  RecipeAssets(
      id: 19,
      name: "كيش بالدجاج",
      image: RecipesImage.sideDishe19,
      cookingTime: 60,
      mealsNo: 8,
      ingredients: RecipesIngredients.sideDishe19,
      prepare: RecipesPrepare.sideDishe19,
      calories: 210,
      protein: 10,
      fat: 15,
      carb: 8),
  RecipeAssets(
      id: 20,
      name: "محشي البصل بالبرغل واللحم المفروم",
      image: RecipesImage.sideDishe20,
      cookingTime: 70,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe20,
      prepare: RecipesPrepare.sideDishe20,
      calories: 190,
      protein: 8,
      fat: 12,
      carb: 13),
  RecipeAssets(
      id: 21,
      name: "المكرونة بالبصل دون طماطم",
      image: RecipesImage.sideDishe21,
      cookingTime: 35,
      mealsNo: 4,
      ingredients: RecipesIngredients.sideDishe21,
      prepare: RecipesPrepare.sideDishe21,
      calories: 530,
      protein: 17,
      fat: 10,
      carb: 95),
  RecipeAssets(
      id: 22,
      name: "كرات البطاطس المقرمشة",
      image: RecipesImage.sideDishe22,
      cookingTime: 80,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe22,
      prepare: RecipesPrepare.sideDishe22,
      calories: 236,
      protein: 6,
      fat: 1,
      carb: 53),
  RecipeAssets(
      id: 23,
      name: "بوكاديوس بالطون",
      image: RecipesImage.sideDishe23,
      cookingTime: 45,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe23,
      prepare: RecipesPrepare.sideDishe23,
      calories: 380,
      protein: 30,
      fat: 8,
      carb: 46),
  RecipeAssets(
      id: 24,
      name: "كيش بالخضار",
      image: RecipesImage.sideDishe24,
      cookingTime: 180,
      mealsNo: 10,
      ingredients: RecipesIngredients.sideDishe24,
      prepare: RecipesPrepare.sideDishe24,
      calories: 232,
      protein: 12,
      fat: 11,
      carb: 23),
  RecipeAssets(
      id: 25,
      name: "كفتة الجمبري البورسعيدية",
      image: RecipesImage.sideDishe25,
      cookingTime: 30,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe25,
      prepare: RecipesPrepare.sideDishe25,
      calories: 166,
      protein: 20,
      fat: 2,
      carb: 10),
  RecipeAssets(
      id: 26,
      name: "فطيرة الأجبان",
      image: RecipesImage.sideDishe26,
      cookingTime: 90,
      mealsNo: 8,
      ingredients: RecipesIngredients.sideDishe26,
      prepare: RecipesPrepare.sideDishe26,
      calories: 412,
      protein: 15,
      fat: 25,
      carb: 32),
  RecipeAssets(
      id: 27,
      name: "اليالنجي اللبناني",
      image: RecipesImage.sideDishe27,
      cookingTime: 160,
      mealsNo: 12,
      ingredients: RecipesIngredients.sideDishe27,
      prepare: RecipesPrepare.sideDishe27,
      calories: 205,
      protein: 5,
      fat: 8,
      carb: 30),
  RecipeAssets(
      id: 28,
      name: "خلية النحل بالجبن",
      image: RecipesImage.sideDishe28,
      cookingTime: 120,
      mealsNo: 8,
      ingredients: RecipesIngredients.sideDishe28,
      prepare: RecipesPrepare.sideDishe28,
      calories: 571,
      protein: 25,
      fat: 26,
      carb: 58),
  RecipeAssets(
      id: 29,
      name: "رول البطاطس باللحمة المفرومة",
      image: RecipesImage.sideDishe29,
      cookingTime: 80,
      mealsNo: 8,
      ingredients: RecipesIngredients.sideDishe29,
      prepare: RecipesPrepare.sideDishe29,
      calories: 227,
      protein: 17,
      fat: 12,
      carb: 11),
  RecipeAssets(
      id: 30,
      name: "ورق عنب عراقي",
      image: RecipesImage.sideDishe30,
      cookingTime: 90,
      mealsNo: 6,
      ingredients: RecipesIngredients.sideDishe30,
      prepare: RecipesPrepare.sideDishe30,
      calories: 480,
      protein: 11,
      fat: 16,
      carb: 76),
];
final List<RecipeAssets> dessertsRecipesList = [
  RecipeAssets(
      id: 1,
      name: "تشيز كيك ريد فيلفيت",
      image: RecipesImage.dessert1,
      cookingTime: 120,
      mealsNo: 12,
      ingredients: RecipesIngredients.dessert1,
      prepare: RecipesPrepare.dessert1,
      calories: 330,
      protein: 6,
      fat: 28,
      carb: 28),
  RecipeAssets(
      id: 2,
      name: "كيكة التمر بالتوفي",
      image: RecipesImage.dessert2,
      cookingTime: 90,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert2,
      prepare: RecipesPrepare.dessert2,
      calories: 443,
      protein: 7,
      fat: 17,
      carb: 67),
  RecipeAssets(
      id: 3,
      name: "كيكة الشوكولاتة دون بيض",
      image: RecipesImage.dessert3,
      cookingTime: 50,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert3,
      prepare: RecipesPrepare.dessert3,
      calories: 240,
      protein: 4,
      fat: 11,
      carb: 35),
  RecipeAssets(
      id: 4,
      name: "العريكة الجنوبية",
      image: RecipesImage.dessert4,
      cookingTime: 60,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert4,
      prepare: RecipesPrepare.dessert4,
      calories: 250,
      protein: 4,
      fat: 5,
      carb: 50),
  RecipeAssets(
      id: 5,
      name: "بسبوسة بالمانجو",
      image: RecipesImage.dessert5,
      cookingTime: 45,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert5,
      prepare: RecipesPrepare.dessert5,
      calories: 310,
      protein: 7,
      fat: 8,
      carb: 52),
  RecipeAssets(
      id: 6,
      name: "الكب كيك دون فرن",
      image: RecipesImage.dessert6,
      cookingTime: 40,
      mealsNo: 6,
      ingredients: RecipesIngredients.dessert6,
      prepare: RecipesPrepare.dessert6,
      calories: 160,
      protein: 4,
      fat: 10,
      carb: 20),
  RecipeAssets(
      id: 7,
      name: "كيكة التوفي بجوز الهند",
      image: RecipesImage.dessert7,
      cookingTime: 90,
      mealsNo: 8,
      ingredients: RecipesIngredients.dessert7,
      prepare: RecipesPrepare.dessert7,
      calories: 380,
      protein: 5,
      fat: 20,
      carb: 50),
  RecipeAssets(
      id: 8,
      name: "كيكة الرمل",
      image: RecipesImage.dessert8,
      cookingTime: 60,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert8,
      prepare: RecipesPrepare.dessert8,
      calories: 235,
      protein: 7,
      fat: 8,
      carb: 33),
  RecipeAssets(
      id: 9,
      name: "تشيز كيك ياباني",
      image: RecipesImage.dessert9,
      cookingTime: 80,
      mealsNo: 6,
      ingredients: RecipesIngredients.dessert9,
      prepare: RecipesPrepare.dessert9,
      calories: 440,
      protein: 15,
      fat: 26,
      carb: 36),
  RecipeAssets(
      id: 10,
      name: "تشيز كيك تونسي",
      image: RecipesImage.dessert10,
      cookingTime: 30,
      mealsNo: 8,
      ingredients: RecipesIngredients.dessert10,
      prepare: RecipesPrepare.dessert10,
      calories: 500,
      protein: 7,
      fat: 34,
      carb: 40),
  RecipeAssets(
      id: 11,
      name: "تارت البسكوت دون بيض",
      image: RecipesImage.dessert11,
      cookingTime: 45,
      mealsNo: 8,
      ingredients: RecipesIngredients.dessert11,
      prepare: RecipesPrepare.dessert11,
      calories: 635,
      protein: 10,
      fat: 37,
      carb: 70),
  RecipeAssets(
      id: 12,
      name: "آيس كريم كيتو",
      image: RecipesImage.dessert12,
      cookingTime: 5,
      mealsNo: 2,
      ingredients: RecipesIngredients.dessert12,
      prepare: RecipesPrepare.dessert12,
      calories: 85,
      protein: 5,
      fat: 1,
      carb: 14),
  RecipeAssets(
      id: 13,
      name: "تشيز كيك بالمانجو",
      image: RecipesImage.dessert13,
      cookingTime: 180,
      mealsNo: 12,
      ingredients: RecipesIngredients.dessert13,
      prepare: RecipesPrepare.dessert13,
      calories: 424,
      protein: 7,
      fat: 22,
      carb: 50),
  RecipeAssets(
      id: 14,
      name: "كيك الحليب المحموس والسميد",
      image: RecipesImage.dessert14,
      cookingTime: 60,
      mealsNo: 12,
      ingredients: RecipesIngredients.dessert14,
      prepare: RecipesPrepare.dessert14,
      calories: 280,
      protein: 7,
      fat: 15,
      carb: 35),
  RecipeAssets(
      id: 15,
      name: "كوكيز الشوفان بالموز",
      image: RecipesImage.dessert15,
      cookingTime: 30,
      mealsNo: 7,
      ingredients: RecipesIngredients.dessert15,
      prepare: RecipesPrepare.dessert15,
      calories: 141,
      protein: 2,
      fat: 5,
      carb: 22),
  RecipeAssets(
      id: 16,
      name: "بسبوسة بالقشطة",
      image: RecipesImage.dessert16,
      cookingTime: 30,
      mealsNo: 5,
      ingredients: RecipesIngredients.dessert16,
      prepare: RecipesPrepare.dessert16,
      calories: 525,
      protein: 8,
      fat: 17,
      carb: 88),
  RecipeAssets(
      id: 17,
      name: "دونات محشي كاسترد",
      image: RecipesImage.dessert17,
      cookingTime: 20,
      mealsNo: 9,
      ingredients: RecipesIngredients.dessert17,
      prepare: RecipesPrepare.dessert17,
      calories: 332,
      protein: 8,
      fat: 11,
      carb: 48),
  RecipeAssets(
      id: 18,
      name: "الدونات المقلية دون بيض",
      image: RecipesImage.dessert18,
      cookingTime: 60,
      mealsNo: 4,
      ingredients: RecipesIngredients.dessert18,
      prepare: RecipesPrepare.dessert18,
      calories: 410,
      protein: 10,
      fat: 7,
      carb: 76),
  RecipeAssets(
      id: 19,
      name: "كرات الدونات",
      image: RecipesImage.dessert19,
      cookingTime: 30,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert19,
      prepare: RecipesPrepare.dessert19,
      calories: 223,
      protein: 5,
      fat: 6,
      carb: 38),
  RecipeAssets(
      id: 20,
      name: "حلى اللبنية بالبسكويت الناعم",
      image: RecipesImage.dessert20,
      cookingTime: 40,
      mealsNo: 16,
      ingredients: RecipesIngredients.dessert20,
      prepare: RecipesPrepare.dessert20,
      calories: 221,
      protein: 4,
      fat: 11,
      carb: 25),
  RecipeAssets(
      id: 21,
      name: "بان كيك الشوفان دون بيض",
      image: RecipesImage.dessert21,
      cookingTime: 30,
      mealsNo: 4,
      ingredients: RecipesIngredients.dessert21,
      prepare: RecipesPrepare.dessert21,
      calories: 240,
      protein: 8,
      fat: 4,
      carb: 43),
  RecipeAssets(
      id: 22,
      name: "المعمول السوري بالسميد",
      image: RecipesImage.dessert22,
      cookingTime: 20,
      mealsNo: 4,
      ingredients: RecipesIngredients.dessert22,
      prepare: RecipesPrepare.dessert22,
      calories: 90,
      protein: 1,
      fat: 4,
      carb: 12),
  RecipeAssets(
      id: 23,
      name: "تمرية بالبسكويت",
      image: RecipesImage.dessert23,
      cookingTime: 25,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert23,
      prepare: RecipesPrepare.dessert23,
      calories: 500,
      protein: 6,
      fat: 23,
      carb: 65),
  RecipeAssets(
      id: 24,
      name: "حلى السميد والحليب المحموس",
      image: RecipesImage.dessert24,
      cookingTime: 30,
      mealsNo: 8,
      ingredients: RecipesIngredients.dessert24,
      prepare: RecipesPrepare.dessert24,
      calories: 208,
      protein: 9,
      fat: 4,
      carb: 35),
  RecipeAssets(
      id: 25,
      name: "أصابع زينب دون سميد",
      image: RecipesImage.dessert25,
      cookingTime: 30,
      mealsNo: 4,
      ingredients: RecipesIngredients.dessert25,
      prepare: RecipesPrepare.dessert25,
      calories: 515,
      protein: 8,
      fat: 18,
      carb: 80),
  RecipeAssets(
      id: 26,
      name: "بسبوسة التمر دون بيض",
      image: RecipesImage.dessert26,
      cookingTime: 30,
      mealsNo: 6,
      ingredients: RecipesIngredients.dessert26,
      prepare: RecipesPrepare.dessert26,
      calories: 310,
      protein: 8,
      fat: 11,
      carb: 45),
  RecipeAssets(
      id: 27,
      name: "كريب براونيز",
      image: RecipesImage.dessert27,
      cookingTime: 30,
      mealsNo: 5,
      ingredients: RecipesIngredients.dessert27,
      prepare: RecipesPrepare.dessert27,
      calories: 501,
      protein: 13,
      fat: 14,
      carb: 91),
  RecipeAssets(
      id: 28,
      name: "حلى سمورز",
      image: RecipesImage.dessert28,
      cookingTime: 60,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert28,
      prepare: RecipesPrepare.dessert28,
      calories: 570,
      protein: 6,
      fat: 33,
      carb: 63),
  RecipeAssets(
      id: 29,
      name: "مهلبية النسكافيه",
      image: RecipesImage.dessert29,
      cookingTime: 15,
      mealsNo: 10,
      ingredients: RecipesIngredients.dessert29,
      prepare: RecipesPrepare.dessert29,
      calories: 123,
      protein: 3,
      fat: 3,
      carb: 23),
  RecipeAssets(
      id: 30,
      name: "تشيز كيك الشوكولاتة",
      image: RecipesImage.dessert30,
      cookingTime: 90,
      mealsNo: 12,
      ingredients: RecipesIngredients.dessert30,
      prepare: RecipesPrepare.dessert30,
      calories: 121,
      protein: 4,
      fat: 8,
      carb: 11),
];

final List<RecipeAssets> breakfastDishesList = [
  RecipeAssets(
      id: 1,
      name: "الخبز  الياباني",
      image: RecipesImage.breakfastDishe1,
      cookingTime: 120,
      mealsNo: 16,
      ingredients: RecipesIngredients.breakfastDishe1,
      prepare: RecipesPrepare.breakfastDishe1,
      calories: 112,
      protein: 3,
      fat: 3,
      carb: 19),
  RecipeAssets(
      id: 2,
      name: "الكريب الفرنسي",
      image: RecipesImage.breakfastDishe2,
      cookingTime: 35,
      mealsNo: 10,
      ingredients: RecipesIngredients.breakfastDishe2,
      prepare: RecipesPrepare.breakfastDishe2,
      calories: 127,
      protein: 4,
      fat: 5,
      carb: 16),
  RecipeAssets(
      id: 3,
      name: "جيب التاجر بالتونة",
      image: RecipesImage.breakfastDishe3,
      cookingTime: 30,
      mealsNo: 8,
      ingredients: RecipesIngredients.breakfastDishe3,
      prepare: RecipesPrepare.breakfastDishe3,
      calories: 178,
      protein: 13,
      fat: 4,
      carb: 24),
  RecipeAssets(
      id: 4,
      name: "خبز البابكا بالشوكولاتة",
      image: RecipesImage.breakfastDishe4,
      cookingTime: 50,
      mealsNo: 4,
      ingredients: RecipesIngredients.breakfastDishe4,
      prepare: RecipesPrepare.breakfastDishe4,
      calories: 820,
      protein: 21,
      fat: 30,
      carb: 114),
  RecipeAssets(
      id: 5,
      name: "الكرنتيكا الجزائرية",
      image: RecipesImage.breakfastDishe5,
      cookingTime: 10,
      mealsNo: 2,
      ingredients: RecipesIngredients.breakfastDishe5,
      prepare: RecipesPrepare.breakfastDishe5,
      calories: 635,
      protein: 13,
      fat: 22,
      carb: 95),
  RecipeAssets(
      id: 6,
      name: "المربى الدايت",
      image: RecipesImage.breakfastDishe6,
      cookingTime: 40,
      mealsNo: 10,
      ingredients: RecipesIngredients.breakfastDishe6,
      prepare: RecipesPrepare.breakfastDishe6,
      calories: 21,
      protein: 1,
      fat: 0,
      carb: 5),
  RecipeAssets(
      id: 7,
      name: "مربى الرمان",
      image: RecipesImage.breakfastDishe7,
      cookingTime: 40,
      mealsNo: 8,
      ingredients: RecipesIngredients.breakfastDishe7,
      prepare: RecipesPrepare.breakfastDishe7,
      calories: 73,
      protein: 1,
      fat: 0,
      carb: 17),
  RecipeAssets(
      id: 8,
      name: "عجة كرفس بالبيض والزعفران",
      image: RecipesImage.breakfastDishe8,
      cookingTime: 8,
      mealsNo: 2,
      ingredients: RecipesIngredients.breakfastDishe8,
      prepare: RecipesPrepare.breakfastDishe8,
      calories: 204,
      protein: 13,
      fat: 16,
      carb: 1),
  RecipeAssets(
      id: 9,
      name: "سندويشات اللحم المقدد للكيتو",
      image: RecipesImage.breakfastDishe9,
      cookingTime: 10,
      mealsNo: 1,
      ingredients: RecipesIngredients.breakfastDishe9,
      prepare: RecipesPrepare.breakfastDishe9,
      calories: 489,
      protein: 29,
      fat: 35,
      carb: 19),
  RecipeAssets(
      id: 10,
      name: "البغرير الجزائري",
      image: RecipesImage.breakfastDishe10,
      cookingTime: 8,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe10,
      prepare: RecipesPrepare.breakfastDishe10,
      calories: 423,
      protein: 12,
      fat: 9,
      carb: 72),
  RecipeAssets(
      id: 11,
      name: "لفائف البيض الكوري",
      image: RecipesImage.breakfastDishe11,
      cookingTime: 25,
      mealsNo: 3,
      ingredients: RecipesIngredients.breakfastDishe11,
      prepare: RecipesPrepare.breakfastDishe11,
      calories: 173,
      protein: 11,
      fat: 12,
      carb: 4),
  RecipeAssets(
      id: 12,
      name: "زبدة الفول السوداني للكيتو",
      image: RecipesImage.breakfastDishe12,
      cookingTime: 30,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe12,
      prepare: RecipesPrepare.breakfastDishe12,
      calories: 567,
      protein: 17,
      fat: 32,
      carb: 11),
  RecipeAssets(
      id: 13,
      name: "بسكويت اللوتس",
      image: RecipesImage.breakfastDishe13,
      cookingTime: 35,
      mealsNo: 5,
      ingredients: RecipesIngredients.breakfastDishe13,
      prepare: RecipesPrepare.breakfastDishe13,
      calories: 346,
      protein: 6,
      fat: 10,
      carb: 59),
  RecipeAssets(
      id: 14,
      name: "القرص الفلاحي بالعجوة",
      image: RecipesImage.breakfastDishe14,
      cookingTime: 120,
      mealsNo: 8,
      ingredients: RecipesIngredients.breakfastDishe14,
      prepare: RecipesPrepare.breakfastDishe14,
      calories: 394,
      protein: 8,
      fat: 12,
      carb: 63),
  RecipeAssets(
      id: 15,
      name: "كريب كيتو",
      image: RecipesImage.breakfastDishe15,
      cookingTime: 30,
      mealsNo: 4,
      ingredients: RecipesIngredients.breakfastDishe15,
      prepare: RecipesPrepare.breakfastDishe15,
      calories: 237,
      protein: 11,
      fat: 14,
      carb: 17),
  RecipeAssets(
      id: 16,
      name: "أومليت الكاب كيك",
      image: RecipesImage.breakfastDishe16,
      cookingTime: 30,
      mealsNo: 12,
      ingredients: RecipesIngredients.breakfastDishe16,
      prepare: RecipesPrepare.breakfastDishe16,
      calories: 90,
      protein: 7,
      fat: 6,
      carb: 3),
  RecipeAssets(
      id: 17,
      name: "كاليط بالعسل",
      image: RecipesImage.breakfastDishe17,
      cookingTime: 60,
      mealsNo: 8,
      ingredients: RecipesIngredients.breakfastDishe17,
      prepare: RecipesPrepare.breakfastDishe17,
      calories: 350,
      protein: 7,
      fat: 8,
      carb: 62),
  RecipeAssets(
      id: 18,
      name: "بطاطس مقلية بالبهارات",
      image: RecipesImage.breakfastDishe18,
      cookingTime: 45,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe18,
      prepare: RecipesPrepare.breakfastDishe18,
      calories: 157,
      protein: 2,
      fat: 9,
      carb: 17),
  RecipeAssets(
      id: 19,
      name: "الفول بالطريقة السودانية",
      image: RecipesImage.breakfastDishe19,
      cookingTime: 30,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe19,
      prepare: RecipesPrepare.breakfastDishe19,
      calories: 800,
      protein: 45,
      fat: 12,
      carb: 104),
  RecipeAssets(
      id: 20,
      name: "كينوا بالحليب",
      image: RecipesImage.breakfastDishe20,
      cookingTime: 20,
      mealsNo: 2,
      ingredients: RecipesIngredients.breakfastDishe20,
      prepare: RecipesPrepare.breakfastDishe20,
      calories: 408,
      protein: 16,
      fat: 12,
      carb: 70),
  RecipeAssets(
      id: 21,
      name: "فول القلابة",
      image: RecipesImage.breakfastDishe21,
      cookingTime: 30,
      mealsNo: 5,
      ingredients: RecipesIngredients.breakfastDishe21,
      prepare: RecipesPrepare.breakfastDishe21,
      calories: 308,
      protein: 21,
      fat: 4,
      carb: 49),
  RecipeAssets(
      id: 22,
      name: "جبنة التوفو",
      image: RecipesImage.breakfastDishe22,
      cookingTime: 30,
      mealsNo: 4,
      ingredients: RecipesIngredients.breakfastDishe22,
      prepare: RecipesPrepare.breakfastDishe22,
      calories: 235,
      protein: 17,
      fat: 13,
      carb: 17),
  RecipeAssets(
      id: 23,
      name: "الطعمية المصرية مثل المطاعم",
      image: RecipesImage.breakfastDishe23,
      cookingTime: 60,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe23,
      prepare: RecipesPrepare.breakfastDishe23,
      calories: 213,
      protein: 9,
      fat: 12,
      carb: 19),
  RecipeAssets(
      id: 24,
      name: "البان كيك الأمريكي",
      image: RecipesImage.breakfastDishe24,
      cookingTime: 30,
      mealsNo: 4,
      ingredients: RecipesIngredients.breakfastDishe24,
      prepare: RecipesPrepare.breakfastDishe24,
      calories: 261,
      protein: 7,
      fat: 8,
      carb: 40),
  RecipeAssets(
      id: 25,
      name: "الزبادي اليوناني في البيت",
      image: RecipesImage.breakfastDishe25,
      cookingTime: 90,
      mealsNo: 8,
      ingredients: RecipesIngredients.breakfastDishe25,
      prepare: RecipesPrepare.breakfastDishe25,
      calories: 56,
      protein: 4,
      fat: 3,
      carb: 6),
  RecipeAssets(
      id: 26,
      name: "تارت الشوفان بالزبادي",
      image: RecipesImage.breakfastDishe26,
      cookingTime: 60,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe26,
      prepare: RecipesPrepare.breakfastDishe26,
      calories: 249,
      protein: 8,
      fat: 4,
      carb: 45),
  RecipeAssets(
      id: 27,
      name: "بيض بالبلوبيف",
      image: RecipesImage.breakfastDishe27,
      cookingTime: 20,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe27,
      prepare: RecipesPrepare.breakfastDishe27,
      calories: 147,
      protein: 13,
      fat: 9,
      carb: 3),
  RecipeAssets(
      id: 28,
      name: "بيض بالبطاطس المسلوقة",
      image: RecipesImage.breakfastDishe28,
      cookingTime: 30,
      mealsNo: 5,
      ingredients: RecipesIngredients.breakfastDishe28,
      prepare: RecipesPrepare.breakfastDishe28,
      calories: 170,
      protein: 8,
      fat: 13,
      carb: 4),
  RecipeAssets(
      id: 29,
      name: "بيض بالشوفان",
      image: RecipesImage.breakfastDishe29,
      cookingTime: 20,
      mealsNo: 4,
      ingredients: RecipesIngredients.breakfastDishe29,
      prepare: RecipesPrepare.breakfastDishe29,
      calories: 144,
      protein: 8,
      fat: 8,
      carb: 9),
  RecipeAssets(
      id: 30,
      name: "مافن الشوفان بالموز والفاكهة",
      image: RecipesImage.breakfastDishe30,
      cookingTime: 60,
      mealsNo: 6,
      ingredients: RecipesIngredients.breakfastDishe30,
      prepare: RecipesPrepare.breakfastDishe30,
      calories: 283,
      protein: 15,
      fat: 7,
      carb: 46),
];
final List<RecipeAssets> sosDishesList = [
  RecipeAssets(
      id: 1,
      name: "صوص الأفوكادو للفاهيتا",
      image: RecipesImage.sos1,
      cookingTime: 8,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos1,
      prepare: RecipesPrepare.sos1,
      calories: 73,
      protein: 0,
      fat: 7,
      carb: 3),
  RecipeAssets(
      id: 2,
      name: "صوص الشاورما بالجبن",
      image: RecipesImage.sos2,
      cookingTime: 15,
      mealsNo: 4,
      ingredients: RecipesIngredients.sos2,
      prepare: RecipesPrepare.sos2,
      calories: 364,
      protein: 17,
      fat: 27,
      carb: 14),
  RecipeAssets(
      id: 3,
      name: "صوص الفاهيتا بالزبادي",
      image: RecipesImage.sos3,
      cookingTime: 8,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos3,
      prepare: RecipesPrepare.sos3,
      calories: 24,
      protein: 2,
      fat: 1,
      carb: 2),
  RecipeAssets(
      id: 4,
      name: "صوص السمبوسة الهندية",
      image: RecipesImage.sos4,
      cookingTime: 10,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos4,
      prepare: RecipesPrepare.sos4,
      calories: 54,
      protein: 3,
      fat: 2,
      carb: 4),
  RecipeAssets(
      id: 5,
      name: "صوص الشاورما التركية",
      image: RecipesImage.sos5,
      cookingTime: 40,
      mealsNo: 4,
      ingredients: RecipesIngredients.sos5,
      prepare: RecipesPrepare.sos5,
      calories: 63,
      protein: 2,
      fat: 5,
      carb: 5),
  RecipeAssets(
      id: 6,
      name: "طحينة الكيتو",
      image: RecipesImage.sos6,
      cookingTime: 5,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos6,
      prepare: RecipesPrepare.sos6,
      calories: 71,
      protein: 0,
      fat: 6,
      carb: 3),
  RecipeAssets(
      id: 7,
      name: "صلصة المايونيز بالحبق والليمون الحامض",
      image: RecipesImage.sos7,
      cookingTime: 5,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos7,
      prepare: RecipesPrepare.sos7,
      calories: 453,
      protein: 1,
      fat: 50,
      carb: 0),
  RecipeAssets(
      id: 8,
      name: "سيراتشا صوص",
      image: RecipesImage.sos8,
      cookingTime: 25,
      mealsNo: 18,
      ingredients: RecipesIngredients.sos8,
      prepare: RecipesPrepare.sos8,
      calories: 16,
      protein: 0,
      fat: 0,
      carb: 4),
  RecipeAssets(
      id: 9,
      name: "صوص الناتشوز",
      image: RecipesImage.sos9,
      cookingTime: 10,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos9,
      prepare: RecipesPrepare.sos9,
      calories: 197,
      protein: 10,
      fat: 15,
      carb: 5),
  RecipeAssets(
      id: 10,
      name: "صوص الترياكي",
      image: RecipesImage.sos10,
      cookingTime: 15,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos10,
      prepare: RecipesPrepare.sos10,
      calories: 85,
      protein: 0,
      fat: 0,
      carb: 21),
  RecipeAssets(
      id: 11,
      name: "صوص السمك المشوي",
      image: RecipesImage.sos11,
      cookingTime: 5,
      mealsNo: 2,
      ingredients: RecipesIngredients.sos11,
      prepare: RecipesPrepare.sos11,
      calories: 180,
      protein: 0,
      fat: 14,
      carb: 16),
  RecipeAssets(
      id: 12,
      name: "الثوم اللبناني",
      image: RecipesImage.sos12,
      cookingTime: 15,
      mealsNo: 18,
      ingredients: RecipesIngredients.sos12,
      prepare: RecipesPrepare.sos12,
      calories: 39,
      protein: 1,
      fat: 2,
      carb: 3),
  RecipeAssets(
      id: 13,
      name: "صوص الشوكولاتة البيضاء",
      image: RecipesImage.sos13,
      cookingTime: 15,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos13,
      prepare: RecipesPrepare.sos13,
      calories: 245,
      protein: 3,
      fat: 13,
      carb: 27),
  RecipeAssets(
      id: 14,
      name: "صوص الربيان",
      image: RecipesImage.sos14,
      cookingTime: 10,
      mealsNo: 8,
      ingredients: RecipesIngredients.sos14,
      prepare: RecipesPrepare.sos14,
      calories: 376,
      protein: 0,
      fat: 50,
      carb: 13),
  RecipeAssets(
      id: 15,
      name: "اللبن المكثف باللبن الحليب",
      image: RecipesImage.sos15,
      cookingTime: 35,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos15,
      prepare: RecipesPrepare.sos15,
      calories: 142,
      protein: 2,
      fat: 9,
      carb: 15),
  RecipeAssets(
      id: 16,
      name: "شوكولاتة لتزيين الكيك",
      image: RecipesImage.sos16,
      cookingTime: 15,
      mealsNo: 4,
      ingredients: RecipesIngredients.sos16,
      prepare: RecipesPrepare.sos16,
      calories: 195,
      protein: 3,
      fat: 6,
      carb: 34),
  RecipeAssets(
      id: 17,
      name: "الكراميل بالسكر",
      image: RecipesImage.sos17,
      cookingTime: 15,
      mealsNo: 1,
      ingredients: RecipesIngredients.sos17,
      prepare: RecipesPrepare.sos17,
      calories: 964,
      protein: 8,
      fat: 26,
      carb: 185),
  RecipeAssets(
      id: 18,
      name: "صوص الزبادي للسلطة",
      image: RecipesImage.sos18,
      cookingTime: 10,
      mealsNo: 2,
      ingredients: RecipesIngredients.sos18,
      prepare: RecipesPrepare.sos18,
      calories: 222,
      protein: 5,
      fat: 17,
      carb: 14),
  RecipeAssets(
      id: 19,
      name: "صوص الشوكولاتة",
      image: RecipesImage.sos19,
      cookingTime: 25,
      mealsNo: 7,
      ingredients: RecipesIngredients.sos19,
      prepare: RecipesPrepare.sos19,
      calories: 233,
      protein: 4,
      fat: 11,
      carb: 30),
  RecipeAssets(
      id: 20,
      name: "صوص الرانش",
      image: RecipesImage.sos20,
      cookingTime: 30,
      mealsNo: 8,
      ingredients: RecipesIngredients.sos20,
      prepare: RecipesPrepare.sos20,
      calories: 182,
      protein: 1,
      fat: 16,
      carb: 2),
  RecipeAssets(
      id: 21,
      name: "صلصة الكشري",
      image: RecipesImage.sos21,
      cookingTime: 30,
      mealsNo: 5,
      ingredients: RecipesIngredients.sos21,
      prepare: RecipesPrepare.sos21,
      calories: 120,
      protein: 3,
      fat: 6,
      carb: 15),
  RecipeAssets(
      id: 2,
      name: "خلطة كنتاكي",
      mealsNo: 2,
      cookingTime: 15,
      image: RecipesImage.mainDishe2,
      ingredients: RecipesIngredients.mainDishe2,
      prepare: RecipesPrepare.mainDishe2,
      calories: 819,
      protein: 22,
      fat: 2,
      carb: 21),
  RecipeAssets(
      id: 22,
      name: "صوص ثاوزند آيلاند",
      image: RecipesImage.sos22,
      cookingTime: 20,
      mealsNo: 5,
      ingredients: RecipesIngredients.sos22,
      prepare: RecipesPrepare.sos22,
      calories: 148,
      protein: 3,
      fat: 12,
      carb: 6),
  RecipeAssets(
      id: 23,
      name: "صوص التيرامسيو",
      image: RecipesImage.sos23,
      cookingTime: 25,
      mealsNo: 8,
      ingredients: RecipesIngredients.sos23,
      prepare: RecipesPrepare.sos23,
      calories: 184,
      protein: 4,
      fat: 15,
      carb: 11),
  RecipeAssets(
      id: 24,
      name: "صوص الرامن",
      image: RecipesImage.sos24,
      cookingTime: 10,
      mealsNo: 2,
      ingredients: RecipesIngredients.sos24,
      prepare: RecipesPrepare.sos24,
      calories: 130,
      protein: 5,
      fat: 10,
      carb: 5),
  RecipeAssets(
      id: 25,
      name: "صوص الكرسبي",
      image: RecipesImage.sos25,
      cookingTime: 5,
      mealsNo: 4,
      ingredients: RecipesIngredients.sos25,
      prepare: RecipesPrepare.sos25,
      calories: 92,
      protein: 2,
      fat: 8,
      carb: 4),
  RecipeAssets(
      id: 26,
      name: "صوص الروبيان",
      image: RecipesImage.sos26,
      cookingTime: 10,
      mealsNo: 8,
      ingredients: RecipesIngredients.sos26,
      prepare: RecipesPrepare.sos26,
      calories: 195,
      protein: 3,
      fat: 16,
      carb: 11),
  RecipeAssets(
      id: 27,
      name: "صوص الكيك الأبيض",
      image: RecipesImage.sos27,
      cookingTime: 20,
      mealsNo: 8,
      ingredients: RecipesIngredients.sos27,
      prepare: RecipesPrepare.sos27,
      calories: 95,
      protein: 1,
      fat: 3,
      carb: 16),
  RecipeAssets(
      id: 28,
      name: "صوص السوشي الأخضر",
      image: RecipesImage.sos28,
      cookingTime: 5,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos28,
      prepare: RecipesPrepare.sos28,
      calories: 86,
      protein: 2,
      fat: 7,
      carb: 4),
  RecipeAssets(
      id: 29,
      name: "صوص السوشي الأبيض",
      image: RecipesImage.sos29,
      cookingTime: 5,
      mealsNo: 6,
      ingredients: RecipesIngredients.sos29,
      prepare: RecipesPrepare.sos29,
      calories: 151,
      protein: 3,
      fat: 15,
      carb: 1),
  RecipeAssets(
      id: 30,
      name: "صوص السكر للكيك",
      image: RecipesImage.sos30,
      cookingTime: 10,
      mealsNo: 8,
      ingredients: RecipesIngredients.sos30,
      prepare: RecipesPrepare.sos30,
      calories: 87,
      protein: 1,
      fat: 1,
      carb: 22),
];

final List<RecipeAssets> chineseKitchenList = [
  RecipeAssets(
      id: 1,
      name: "نودلز صيني",
      image: "assets/images/recipes/noodles.jpg",
      cookingTime: 30,
      mealsNo: 4,
      ingredients: RecipesIngredients.noodles,
      prepare: RecipesPrepare.noodles,
      calories: 0,
      protein: 0,
      fat: 0,
      carb: 0),
  RecipeAssets(
      id: 2,
      name: "ديناميت شرمب",
      image: "assets/images/recipes/dinametShrimp.jpg",
      cookingTime: 5,
      mealsNo: 1,
      ingredients: RecipesIngredients.noodles,
      prepare: RecipesPrepare.noodles,
      calories: 0,
      protein: 0,
      fat: 0,
      carb: 0),
];
